/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:12 PM CDT 
//

package com.dell.isg.smi.commons.model.vcenter;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ManagedObjectType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ManagedObjectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VCENTER"/>
 *     &lt;enumeration value="FOLDER"/>
 *     &lt;enumeration value="HOST_SYSTEM"/>
 *     &lt;enumeration value="RESOURCE_POOL"/>
 *     &lt;enumeration value="DATACENTER"/>
 *     &lt;enumeration value="CLUSTER"/>
 *     &lt;enumeration value="VIRTUAL_MACHINE"/>
 *     &lt;enumeration value="NETWORK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ManagedObjectType")
@XmlEnum
public enum ManagedObjectType {

    VCENTER, FOLDER, HOST_SYSTEM, RESOURCE_POOL, DATACENTER, CLUSTER, VIRTUAL_MACHINE, NETWORK;

    public String value() {
        return name();
    }


    public static ManagedObjectType fromValue(String v) {
        return valueOf(v);
    }

}
