/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:12 PM CDT 
//

package com.dell.isg.smi.commons.model.vcenter;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * A factory for creating Object objects.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dell.esg.icee.common.pojo.model.vcenter
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link Network }.
     *
     * @return the network
     */
    public Network createNetwork() {
        return new Network();
    }


    /**
     * Create an instance of {@link HostSystem }.
     *
     * @return the host system
     */
    public HostSystem createHostSystem() {
        return new HostSystem();
    }


    /**
     * Create an instance of {@link Datacenter }.
     *
     * @return the datacenter
     */
    public Datacenter createDatacenter() {
        return new Datacenter();
    }


    /**
     * Create an instance of {@link Cluster }.
     *
     * @return the cluster
     */
    public Cluster createCluster() {
        return new Cluster();
    }


    /**
     * Create an instance of {@link ResourcePool }.
     *
     * @return the resource pool
     */
    public ResourcePool createResourcePool() {
        return new ResourcePool();
    }


    /**
     * Create an instance of {@link Folder }.
     *
     * @return the folder
     */
    public Folder createFolder() {
        return new Folder();
    }


    /**
     * Create an instance of {@link VirtualMachine }.
     *
     * @return the virtual machine
     */
    public VirtualMachine createVirtualMachine() {
        return new VirtualMachine();
    }


    /**
     * Create an instance of {@link VCenterDetails }.
     *
     * @return the v center details
     */
    public VCenterDetails createVCenterDetails() {
        return new VCenterDetails();
    }


    /**
     * Create an instance of {@link VCenterSummary }.
     *
     * @return the v center summary
     */
    public VCenterSummary createVCenterSummary() {
        return new VCenterSummary();
    }

}
