/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:12 PM CDT 
//

package com.dell.isg.smi.commons.model.vcenter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class VCenterSummary.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VCenterSummary")
@XmlSeeAlso({ VCenterDetails.class })
public class VCenterSummary extends ManagedObject {

    @XmlAttribute(name = "id")
    protected Long id;
    @XmlAttribute(name = "manufacturer")
    protected String manufacturer;
    @XmlAttribute(name = "ipAddress")
    protected String ipAddress;
    @XmlAttribute(name = "version")
    protected String version;


    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }


    /**
     * Gets the value of the manufacturer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManufacturer() {
        return manufacturer;
    }


    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }


    /**
     * Gets the value of the ipAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIpAddress() {
        return ipAddress;
    }


    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }


    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersion() {
        return version;
    }


    /**
     * Sets the value of the version property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
