/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ArrayToExpansionConnectionUtilization complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayToExpansionConnectionUtilization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connectionHealth" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="arrayConntroller" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expansionPort" type="{http://esg.dell.com/icee/infrastructure/model/storage}StorageEnclosurePort"/>
 *         &lt;element name="bandwidthUsed" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="bandwidthAllocated" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="storageEnclosure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storageEnclosureController" type="{http://esg.dell.com/icee/infrastructure/model/storage}StorageEnclosureController"/>
 *         &lt;element name="storageEnclosurePort" type="{http://esg.dell.com/icee/infrastructure/model/storage}StorageEnclosurePort"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayToExpansionConnectionUtilization", propOrder = { "connectionHealth", "arrayConntroller", "expansionPort", "bandwidthUsed", "bandwidthAllocated", "storageEnclosure", "storageEnclosureController", "storageEnclosurePort" })
public class ArrayToExpansionConnectionUtilization {

    protected boolean connectionHealth;
    protected int arrayConntroller;
    @XmlElement(required = true)
    protected StorageEnclosurePort expansionPort;
    protected long bandwidthUsed;
    protected long bandwidthAllocated;
    @XmlElement(required = true)
    protected String storageEnclosure;
    @XmlElement(required = true)
    protected StorageEnclosureController storageEnclosureController;
    @XmlElement(required = true)
    protected StorageEnclosurePort storageEnclosurePort;


    /**
     * Gets the value of the connectionHealth property.
     * 
     */
    public boolean isConnectionHealth() {
        return connectionHealth;
    }


    /**
     * Sets the value of the connectionHealth property.
     * 
     */
    public void setConnectionHealth(boolean value) {
        this.connectionHealth = value;
    }


    /**
     * Gets the value of the arrayConntroller property.
     * 
     */
    public int getArrayConntroller() {
        return arrayConntroller;
    }


    /**
     * Sets the value of the arrayConntroller property.
     * 
     */
    public void setArrayConntroller(int value) {
        this.arrayConntroller = value;
    }


    /**
     * Gets the value of the expansionPort property.
     * 
     * @return possible object is {@link StorageEnclosurePort }
     * 
     */
    public StorageEnclosurePort getExpansionPort() {
        return expansionPort;
    }


    /**
     * Sets the value of the expansionPort property.
     * 
     * @param value allowed object is {@link StorageEnclosurePort }
     * 
     */
    public void setExpansionPort(StorageEnclosurePort value) {
        this.expansionPort = value;
    }


    /**
     * Gets the value of the bandwidthUsed property.
     * 
     */
    public long getBandwidthUsed() {
        return bandwidthUsed;
    }


    /**
     * Sets the value of the bandwidthUsed property.
     * 
     */
    public void setBandwidthUsed(long value) {
        this.bandwidthUsed = value;
    }


    /**
     * Gets the value of the bandwidthAllocated property.
     * 
     */
    public long getBandwidthAllocated() {
        return bandwidthAllocated;
    }


    /**
     * Sets the value of the bandwidthAllocated property.
     * 
     */
    public void setBandwidthAllocated(long value) {
        this.bandwidthAllocated = value;
    }


    /**
     * Gets the value of the storageEnclosure property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStorageEnclosure() {
        return storageEnclosure;
    }


    /**
     * Sets the value of the storageEnclosure property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStorageEnclosure(String value) {
        this.storageEnclosure = value;
    }


    /**
     * Gets the value of the storageEnclosureController property.
     * 
     * @return possible object is {@link StorageEnclosureController }
     * 
     */
    public StorageEnclosureController getStorageEnclosureController() {
        return storageEnclosureController;
    }


    /**
     * Sets the value of the storageEnclosureController property.
     * 
     * @param value allowed object is {@link StorageEnclosureController }
     * 
     */
    public void setStorageEnclosureController(StorageEnclosureController value) {
        this.storageEnclosureController = value;
    }


    /**
     * Gets the value of the storageEnclosurePort property.
     * 
     * @return possible object is {@link StorageEnclosurePort }
     * 
     */
    public StorageEnclosurePort getStorageEnclosurePort() {
        return storageEnclosurePort;
    }


    /**
     * Sets the value of the storageEnclosurePort property.
     * 
     * @param value allowed object is {@link StorageEnclosurePort }
     * 
     */
    public void setStorageEnclosurePort(StorageEnclosurePort value) {
        this.storageEnclosurePort = value;
    }

}
