/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * The Class ArrayToExpansionConnectionUtilization.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayToExpansionConnectionUtilization", propOrder = { "connectionHealth", "arrayConntroller", "expansionPort", "bandwidthUsed", "bandwidthAllocated", "storageEnclosure", "storageEnclosureController", "storageEnclosurePort" })
public class ArrayToExpansionConnectionUtilization {

    protected boolean connectionHealth;
    protected int arrayConntroller;
    @XmlElement(required = true)
    protected StorageEnclosurePort expansionPort;
    protected long bandwidthUsed;
    protected long bandwidthAllocated;
    @XmlElement(required = true)
    protected String storageEnclosure;
    @XmlElement(required = true)
    protected StorageEnclosureController storageEnclosureController;
    @XmlElement(required = true)
    protected StorageEnclosurePort storageEnclosurePort;


    /**
     * Gets the value of the connectionHealth property.
     *
     * @return true, if is connection health
     */
    public boolean isConnectionHealth() {
        return connectionHealth;
    }


    /**
     * Sets the value of the connectionHealth property.
     *
     * @param value the new connection health
     */
    public void setConnectionHealth(boolean value) {
        this.connectionHealth = value;
    }


    /**
     * Gets the value of the arrayConntroller property.
     *
     * @return the array conntroller
     */
    public int getArrayConntroller() {
        return arrayConntroller;
    }


    /**
     * Sets the value of the arrayConntroller property.
     *
     * @param value the new array conntroller
     */
    public void setArrayConntroller(int value) {
        this.arrayConntroller = value;
    }


    /**
     * Gets the value of the expansionPort property.
     * 
     * @return possible object is {@link StorageEnclosurePort }
     * 
     */
    public StorageEnclosurePort getExpansionPort() {
        return expansionPort;
    }


    /**
     * Sets the value of the expansionPort property.
     * 
     * @param value allowed object is {@link StorageEnclosurePort }
     * 
     */
    public void setExpansionPort(StorageEnclosurePort value) {
        this.expansionPort = value;
    }


    /**
     * Gets the value of the bandwidthUsed property.
     *
     * @return the bandwidth used
     */
    public long getBandwidthUsed() {
        return bandwidthUsed;
    }


    /**
     * Sets the value of the bandwidthUsed property.
     *
     * @param value the new bandwidth used
     */
    public void setBandwidthUsed(long value) {
        this.bandwidthUsed = value;
    }


    /**
     * Gets the value of the bandwidthAllocated property.
     *
     * @return the bandwidth allocated
     */
    public long getBandwidthAllocated() {
        return bandwidthAllocated;
    }


    /**
     * Sets the value of the bandwidthAllocated property.
     *
     * @param value the new bandwidth allocated
     */
    public void setBandwidthAllocated(long value) {
        this.bandwidthAllocated = value;
    }


    /**
     * Gets the value of the storageEnclosure property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStorageEnclosure() {
        return storageEnclosure;
    }


    /**
     * Sets the value of the storageEnclosure property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStorageEnclosure(String value) {
        this.storageEnclosure = value;
    }


    /**
     * Gets the value of the storageEnclosureController property.
     * 
     * @return possible object is {@link StorageEnclosureController }
     * 
     */
    public StorageEnclosureController getStorageEnclosureController() {
        return storageEnclosureController;
    }


    /**
     * Sets the value of the storageEnclosureController property.
     * 
     * @param value allowed object is {@link StorageEnclosureController }
     * 
     */
    public void setStorageEnclosureController(StorageEnclosureController value) {
        this.storageEnclosureController = value;
    }


    /**
     * Gets the value of the storageEnclosurePort property.
     * 
     * @return possible object is {@link StorageEnclosurePort }
     * 
     */
    public StorageEnclosurePort getStorageEnclosurePort() {
        return storageEnclosurePort;
    }


    /**
     * Sets the value of the storageEnclosurePort property.
     * 
     * @param value allowed object is {@link StorageEnclosurePort }
     * 
     */
    public void setStorageEnclosurePort(StorageEnclosurePort value) {
        this.storageEnclosurePort = value;
    }

}
