/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CacheCard complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CacheCard">
 *   &lt;complexContent>
 *     &lt;extension base="{http://esg.dell.com/icee/infrastructure/model/storage}DetailBase">
 *       &lt;sequence>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cacheSize" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="firmwareVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="batteryVoltagePercent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expireStatus" type="{http://esg.dell.com/icee/infrastructure/model/storage}CacheCardExpireStatus"/>
 *         &lt;element name="statusDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CacheCard", propOrder = { "model", "cacheSize", "firmwareVersion", "batteryVoltagePercent", "expireStatus", "statusDescription" })
public class CacheCard extends DetailBase {

    @XmlElement(required = true)
    protected String model;
    protected long cacheSize;
    @XmlElement(required = true)
    protected String firmwareVersion;
    protected int batteryVoltagePercent;
    @XmlElement(required = true)
    protected CacheCardExpireStatus expireStatus;
    @XmlElement(required = true)
    protected String statusDescription;


    /**
     * Gets the value of the model property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModel() {
        return model;
    }


    /**
     * Sets the value of the model property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setModel(String value) {
        this.model = value;
    }


    /**
     * Gets the value of the cacheSize property.
     * 
     */
    public long getCacheSize() {
        return cacheSize;
    }


    /**
     * Sets the value of the cacheSize property.
     * 
     */
    public void setCacheSize(long value) {
        this.cacheSize = value;
    }


    /**
     * Gets the value of the firmwareVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }


    /**
     * Sets the value of the firmwareVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFirmwareVersion(String value) {
        this.firmwareVersion = value;
    }


    /**
     * Gets the value of the batteryVoltagePercent property.
     * 
     */
    public int getBatteryVoltagePercent() {
        return batteryVoltagePercent;
    }


    /**
     * Sets the value of the batteryVoltagePercent property.
     * 
     */
    public void setBatteryVoltagePercent(int value) {
        this.batteryVoltagePercent = value;
    }


    /**
     * Gets the value of the expireStatus property.
     * 
     * @return possible object is {@link CacheCardExpireStatus }
     * 
     */
    public CacheCardExpireStatus getExpireStatus() {
        return expireStatus;
    }


    /**
     * Sets the value of the expireStatus property.
     * 
     * @param value allowed object is {@link CacheCardExpireStatus }
     * 
     */
    public void setExpireStatus(CacheCardExpireStatus value) {
        this.expireStatus = value;
    }


    /**
     * Gets the value of the statusDescription property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatusDescription() {
        return statusDescription;
    }


    /**
     * Sets the value of the statusDescription property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatusDescription(String value) {
        this.statusDescription = value;
    }

}
