/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The Enum ControllerLocation.
 */
@XmlType(name = "ControllerLocation")
@XmlEnum
public enum ControllerLocation {

    @XmlEnumValue("top")
    TOP("top"), @XmlEnumValue("bottom")
    BOTTOM("bottom");
    private final String value;


    /**
     * Instantiates a new controller location.
     *
     * @param v the v
     */
    ControllerLocation(String v) {
        value = v;
    }


    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return value;
    }


    /**
     * From value.
     *
     * @param v the v
     * @return the controller location
     */
    public static ControllerLocation fromValue(String v) {
        for (ControllerLocation c : ControllerLocation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
