/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

// TODO: Auto-generated Javadoc
/**
 * The Class Controller.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Controller", propOrder = { "id", "deviceId", "status", "name", "assetTag", "serviceTag", "model", "version", "availableMemory", "leader", "lastBootTime", "dateInstalled", "dateUpdated", "updatedBy", "health", "cacheCard", "coolingFans", "powerSupplies", "temperatures", "iscsiDetails", "sasDetails" })
public class Controller {

    protected long id;
    @XmlElement(required = true)
    protected String deviceId;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String assetTag;
    @XmlElement(required = true)
    protected String serviceTag;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected String version;
    protected long availableMemory;
    protected boolean leader;
    @XmlElement(required = true)
    protected String lastBootTime;
    @XmlElement(required = true)
    protected String dateInstalled;
    @XmlElement(required = true)
    protected String dateUpdated;
    @XmlElement(required = true)
    protected String updatedBy;
    @XmlElement(required = true)
    protected String health;
    @XmlElement(required = true)
    protected CacheCard cacheCard;
    @XmlElement(required = true)
    protected List<CoolingFan> coolingFans;
    @XmlElement(required = true)
    protected List<PowerSupply> powerSupplies;
    @XmlElement(required = true)
    protected List<Temperature> temperatures;
    @XmlElement(required = true)
    protected List<IscsiDetail> iscsiDetails;
    @XmlElement(required = true)
    protected List<SasDetail> sasDetails;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the deviceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeviceId() {
        return deviceId;
    }


    /**
     * Sets the value of the deviceId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }


    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }


    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the assetTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetTag() {
        return assetTag;
    }


    /**
     * Sets the value of the assetTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAssetTag(String value) {
        this.assetTag = value;
    }


    /**
     * Gets the value of the serviceTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceTag() {
        return serviceTag;
    }


    /**
     * Sets the value of the serviceTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceTag(String value) {
        this.serviceTag = value;
    }


    /**
     * Gets the value of the model property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModel() {
        return model;
    }


    /**
     * Sets the value of the model property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setModel(String value) {
        this.model = value;
    }


    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersion() {
        return version;
    }


    /**
     * Sets the value of the version property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * Gets the value of the availableMemory property.
     *
     * @return the available memory
     */
    public long getAvailableMemory() {
        return availableMemory;
    }


    /**
     * Sets the value of the availableMemory property.
     *
     * @param value the new available memory
     */
    public void setAvailableMemory(long value) {
        this.availableMemory = value;
    }


    /**
     * Gets the value of the leader property.
     *
     * @return true, if is leader
     */
    public boolean isLeader() {
        return leader;
    }


    /**
     * Sets the value of the leader property.
     *
     * @param value the new leader
     */
    public void setLeader(boolean value) {
        this.leader = value;
    }


    /**
     * Gets the value of the lastBootTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastBootTime() {
        return lastBootTime;
    }


    /**
     * Sets the value of the lastBootTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLastBootTime(String value) {
        this.lastBootTime = value;
    }


    /**
     * Gets the value of the dateInstalled property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDateInstalled() {
        return dateInstalled;
    }


    /**
     * Sets the value of the dateInstalled property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDateInstalled(String value) {
        this.dateInstalled = value;
    }


    /**
     * Gets the value of the dateUpdated property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDateUpdated() {
        return dateUpdated;
    }


    /**
     * Sets the value of the dateUpdated property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDateUpdated(String value) {
        this.dateUpdated = value;
    }


    /**
     * Gets the value of the updatedBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpdatedBy() {
        return updatedBy;
    }


    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }


    /**
     * Gets the value of the health property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHealth() {
        return health;
    }


    /**
     * Sets the value of the health property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setHealth(String value) {
        this.health = value;
    }


    /**
     * Gets the value of the cacheCard property.
     * 
     * @return possible object is {@link CacheCard }
     * 
     */
    public CacheCard getCacheCard() {
        return cacheCard;
    }


    /**
     * Sets the value of the cacheCard property.
     * 
     * @param value allowed object is {@link CacheCard }
     * 
     */
    public void setCacheCard(CacheCard value) {
        this.cacheCard = value;
    }


    /**
     * Gets the value of the coolingFans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coolingFans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCoolingFans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CoolingFan }
     *
     * @return the cooling fans
     */
    public List<CoolingFan> getCoolingFans() {
        if (coolingFans == null) {
            coolingFans = new ArrayList<CoolingFan>();
        }
        return this.coolingFans;
    }


    /**
     * Gets the value of the powerSupplies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the powerSupplies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPowerSupplies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link PowerSupply }
     *
     * @return the power supplies
     */
    public List<PowerSupply> getPowerSupplies() {
        if (powerSupplies == null) {
            powerSupplies = new ArrayList<PowerSupply>();
        }
        return this.powerSupplies;
    }


    /**
     * Gets the value of the temperatures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the temperatures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTemperatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Temperature }
     *
     * @return the temperatures
     */
    public List<Temperature> getTemperatures() {
        if (temperatures == null) {
            temperatures = new ArrayList<Temperature>();
        }
        return this.temperatures;
    }


    /**
     * Gets the value of the iscsiDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iscsiDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIscsiDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IscsiDetail }
     *
     * @return the iscsi details
     */
    public List<IscsiDetail> getIscsiDetails() {
        if (iscsiDetails == null) {
            iscsiDetails = new ArrayList<IscsiDetail>();
        }
        return this.iscsiDetails;
    }


    /**
     * Gets the value of the sasDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sasDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSasDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SasDetail }
     *
     * @return the sas details
     */
    public List<SasDetail> getSasDetails() {
        if (sasDetails == null) {
            sasDetails = new ArrayList<SasDetail>();
        }
        return this.sasDetails;
    }

}
