/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CoolingFan complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoolingFan">
 *   &lt;complexContent>
 *     &lt;extension base="{http://esg.dell.com/icee/infrastructure/model/storage}DetailBase">
 *       &lt;sequence>
 *         &lt;element name="swapDetected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="speed" type="{http://esg.dell.com/icee/infrastructure/model/storage}CoolingFanSpeed"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoolingFan", propOrder = { "swapDetected", "location", "speed" })
public class CoolingFan extends DetailBase {

    protected boolean swapDetected;
    @XmlElement(required = true)
    protected String location;
    @XmlElement(required = true)
    protected CoolingFanSpeed speed;


    /**
     * Gets the value of the swapDetected property.
     * 
     */
    public boolean isSwapDetected() {
        return swapDetected;
    }


    /**
     * Sets the value of the swapDetected property.
     * 
     */
    public void setSwapDetected(boolean value) {
        this.swapDetected = value;
    }


    /**
     * Gets the value of the location property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocation() {
        return location;
    }


    /**
     * Sets the value of the location property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLocation(String value) {
        this.location = value;
    }


    /**
     * Gets the value of the speed property.
     * 
     * @return possible object is {@link CoolingFanSpeed }
     * 
     */
    public CoolingFanSpeed getSpeed() {
        return speed;
    }


    /**
     * Sets the value of the speed property.
     * 
     * @param value allowed object is {@link CoolingFanSpeed }
     * 
     */
    public void setSpeed(CoolingFanSpeed value) {
        this.speed = value;
    }

}
