/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class CreateSnapshot.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateSnapshot", propOrder = { "description", "neverExpire", "expireTime", "timeUnit" })
public class CreateSnapshot {

    @XmlElement(required = true)
    protected String description;
    protected boolean neverExpire;
    protected int expireTime;
    @XmlElement(required = true)
    protected TimeUnit timeUnit;


    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
        return description;
    }


    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * Gets the value of the neverExpire property.
     *
     * @return true, if is never expire
     */
    public boolean isNeverExpire() {
        return neverExpire;
    }


    /**
     * Sets the value of the neverExpire property.
     *
     * @param value the new never expire
     */
    public void setNeverExpire(boolean value) {
        this.neverExpire = value;
    }


    /**
     * Gets the value of the expireTime property.
     *
     * @return the expire time
     */
    public int getExpireTime() {
        return expireTime;
    }


    /**
     * Sets the value of the expireTime property.
     *
     * @param value the new expire time
     */
    public void setExpireTime(int value) {
        this.expireTime = value;
    }


    /**
     * Gets the value of the timeUnit property.
     * 
     * @return possible object is {@link TimeUnit }
     * 
     */
    public TimeUnit getTimeUnit() {
        return timeUnit;
    }


    /**
     * Sets the value of the timeUnit property.
     * 
     * @param value allowed object is {@link TimeUnit }
     * 
     */
    public void setTimeUnit(TimeUnit value) {
        this.timeUnit = value;
    }

}
