/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class DateLongValuePair.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateLongValuePair", propOrder = { "date", "value" })
public class DateLongValuePair {

    @XmlElement(required = true)
    protected String date;
    protected long value;


    /**
     * Gets the value of the date property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDate() {
        return date;
    }


    /**
     * Sets the value of the date property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDate(String value) {
        this.date = value;
    }


    /**
     * Gets the value of the value property.
     *
     * @return the value
     */
    public long getValue() {
        return value;
    }


    /**
     * Sets the value of the value property.
     *
     * @param value the new value
     */
    public void setValue(long value) {
        this.value = value;
    }

}
