/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class Detail.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Detail", propOrder = { "overview", "hardwareInventory" })
public class Detail {

    @XmlElement(required = true)
    protected StorageOverview overview;
    @XmlElement(required = true)
    protected StorageHardwareInventory hardwareInventory;


    /**
     * Gets the value of the overview property.
     * 
     * @return possible object is {@link StorageOverview }
     * 
     */
    public StorageOverview getOverview() {
        return overview;
    }


    /**
     * Sets the value of the overview property.
     * 
     * @param value allowed object is {@link StorageOverview }
     * 
     */
    public void setOverview(StorageOverview value) {
        this.overview = value;
    }


    /**
     * Gets the value of the hardwareInventory property.
     * 
     * @return possible object is {@link StorageHardwareInventory }
     * 
     */
    public StorageHardwareInventory getHardwareInventory() {
        return hardwareInventory;
    }


    /**
     * Sets the value of the hardwareInventory property.
     * 
     * @param value allowed object is {@link StorageHardwareInventory }
     * 
     */
    public void setHardwareInventory(StorageHardwareInventory value) {
        this.hardwareInventory = value;
    }

}
