/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class DeviceInformationOverview.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceInformationOverview", propOrder = { "name", "firwareVersion", "diskAlerts", "hardwareAlerts", "systemAlerts", "connectivityAlerts", "licensedFor" })
public class DeviceInformationOverview {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String firwareVersion;
    protected int diskAlerts;
    protected int hardwareAlerts;
    protected int systemAlerts;
    protected int connectivityAlerts;
    @XmlElement(required = true)
    protected String licensedFor;


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the firwareVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirwareVersion() {
        return firwareVersion;
    }


    /**
     * Sets the value of the firwareVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFirwareVersion(String value) {
        this.firwareVersion = value;
    }


    /**
     * Gets the value of the diskAlerts property.
     *
     * @return the disk alerts
     */
    public int getDiskAlerts() {
        return diskAlerts;
    }


    /**
     * Sets the value of the diskAlerts property.
     *
     * @param value the new disk alerts
     */
    public void setDiskAlerts(int value) {
        this.diskAlerts = value;
    }


    /**
     * Gets the value of the hardwareAlerts property.
     *
     * @return the hardware alerts
     */
    public int getHardwareAlerts() {
        return hardwareAlerts;
    }


    /**
     * Sets the value of the hardwareAlerts property.
     *
     * @param value the new hardware alerts
     */
    public void setHardwareAlerts(int value) {
        this.hardwareAlerts = value;
    }


    /**
     * Gets the value of the systemAlerts property.
     *
     * @return the system alerts
     */
    public int getSystemAlerts() {
        return systemAlerts;
    }


    /**
     * Sets the value of the systemAlerts property.
     *
     * @param value the new system alerts
     */
    public void setSystemAlerts(int value) {
        this.systemAlerts = value;
    }


    /**
     * Gets the value of the connectivityAlerts property.
     *
     * @return the connectivity alerts
     */
    public int getConnectivityAlerts() {
        return connectivityAlerts;
    }


    /**
     * Sets the value of the connectivityAlerts property.
     *
     * @param value the new connectivity alerts
     */
    public void setConnectivityAlerts(int value) {
        this.connectivityAlerts = value;
    }


    /**
     * Gets the value of the licensedFor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLicensedFor() {
        return licensedFor;
    }


    /**
     * Sets the value of the licensedFor property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLicensedFor(String value) {
        this.licensedFor = value;
    }

}
