/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Disk complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Disk">
 *   &lt;complexContent>
 *     &lt;extension base="{http://esg.dell.com/icee/infrastructure/model/storage}DetailBase">
 *       &lt;sequence>
 *         &lt;element name="health" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="diskClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="percentFull" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="allocatedSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="freeSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="controlType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Disk", propOrder = { "health", "diskClass", "totalSpace", "percentFull", "allocatedSpace", "freeSpace", "controlType" })
public class Disk extends DetailBase {

    protected boolean health;
    @XmlElement(required = true)
    protected String diskClass;
    protected long totalSpace;
    protected int percentFull;
    protected long allocatedSpace;
    protected long freeSpace;
    @XmlElement(required = true)
    protected String controlType;


    /**
     * Gets the value of the health property.
     * 
     */
    public boolean isHealth() {
        return health;
    }


    /**
     * Sets the value of the health property.
     * 
     */
    public void setHealth(boolean value) {
        this.health = value;
    }


    /**
     * Gets the value of the diskClass property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDiskClass() {
        return diskClass;
    }


    /**
     * Sets the value of the diskClass property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDiskClass(String value) {
        this.diskClass = value;
    }


    /**
     * Gets the value of the totalSpace property.
     * 
     */
    public long getTotalSpace() {
        return totalSpace;
    }


    /**
     * Sets the value of the totalSpace property.
     * 
     */
    public void setTotalSpace(long value) {
        this.totalSpace = value;
    }


    /**
     * Gets the value of the percentFull property.
     * 
     */
    public int getPercentFull() {
        return percentFull;
    }


    /**
     * Sets the value of the percentFull property.
     * 
     */
    public void setPercentFull(int value) {
        this.percentFull = value;
    }


    /**
     * Gets the value of the allocatedSpace property.
     * 
     */
    public long getAllocatedSpace() {
        return allocatedSpace;
    }


    /**
     * Sets the value of the allocatedSpace property.
     * 
     */
    public void setAllocatedSpace(long value) {
        this.allocatedSpace = value;
    }


    /**
     * Gets the value of the freeSpace property.
     * 
     */
    public long getFreeSpace() {
        return freeSpace;
    }


    /**
     * Sets the value of the freeSpace property.
     * 
     */
    public void setFreeSpace(long value) {
        this.freeSpace = value;
    }


    /**
     * Gets the value of the controlType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getControlType() {
        return controlType;
    }


    /**
     * Sets the value of the controlType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setControlType(String value) {
        this.controlType = value;
    }

}
