/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class EnclosuresOverview.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnclosuresOverview", propOrder = { "connected" })
public class EnclosuresOverview {

    protected int connected;


    /**
     * Gets the value of the connected property.
     *
     * @return the connected
     */
    public int getConnected() {
        return connected;
    }


    /**
     * Sets the value of the connected property.
     *
     * @param value the new connected
     */
    public void setConnected(int value) {
        this.connected = value;
    }

}
