/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class FastestGrowningVolume.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FastestGrowningVolume", propOrder = { "id", "name", "healthy", "mappedService", "configured", "size", "growth", "percentFull", "estimatedFullTime", "lastUpdated" })
public class FastestGrowningVolume {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    protected boolean healthy;
    @XmlElement(required = true)
    protected String mappedService;
    protected boolean configured;
    protected long size;
    protected long growth;
    protected float percentFull;
    @XmlElement(required = true)
    protected String estimatedFullTime;
    @XmlElement(required = true)
    protected String lastUpdated;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the healthy property.
     *
     * @return true, if is healthy
     */
    public boolean isHealthy() {
        return healthy;
    }


    /**
     * Sets the value of the healthy property.
     *
     * @param value the new healthy
     */
    public void setHealthy(boolean value) {
        this.healthy = value;
    }


    /**
     * Gets the value of the mappedService property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMappedService() {
        return mappedService;
    }


    /**
     * Sets the value of the mappedService property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMappedService(String value) {
        this.mappedService = value;
    }


    /**
     * Gets the value of the configured property.
     *
     * @return true, if is configured
     */
    public boolean isConfigured() {
        return configured;
    }


    /**
     * Sets the value of the configured property.
     *
     * @param value the new configured
     */
    public void setConfigured(boolean value) {
        this.configured = value;
    }


    /**
     * Gets the value of the size property.
     *
     * @return the size
     */
    public long getSize() {
        return size;
    }


    /**
     * Sets the value of the size property.
     *
     * @param value the new size
     */
    public void setSize(long value) {
        this.size = value;
    }


    /**
     * Gets the value of the growth property.
     *
     * @return the growth
     */
    public long getGrowth() {
        return growth;
    }


    /**
     * Sets the value of the growth property.
     *
     * @param value the new growth
     */
    public void setGrowth(long value) {
        this.growth = value;
    }


    /**
     * Gets the value of the percentFull property.
     *
     * @return the percent full
     */
    public float getPercentFull() {
        return percentFull;
    }


    /**
     * Sets the value of the percentFull property.
     *
     * @param value the new percent full
     */
    public void setPercentFull(float value) {
        this.percentFull = value;
    }


    /**
     * Gets the value of the estimatedFullTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEstimatedFullTime() {
        return estimatedFullTime;
    }


    /**
     * Sets the value of the estimatedFullTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setEstimatedFullTime(String value) {
        this.estimatedFullTime = value;
    }


    /**
     * Gets the value of the lastUpdated property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastUpdated() {
        return lastUpdated;
    }


    /**
     * Sets the value of the lastUpdated property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLastUpdated(String value) {
        this.lastUpdated = value;
    }

}
