/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for IOPort complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IOPort">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ioModules" type="{http://esg.dell.com/icee/infrastructure/model/storage}IoModule" maxOccurs="unbounded"/>
 *         &lt;element name="IscsiDetails" type="{http://esg.dell.com/icee/infrastructure/model/storage}IscsiDetail" maxOccurs="unbounded"/>
 *         &lt;element name="SasDetail" type="{http://esg.dell.com/icee/infrastructure/model/storage}SasDetail" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IOPort", propOrder = { "ioModules", "iscsiDetails", "sasDetail" })
public class IOPort {

    @XmlElement(required = true)
    protected List<IoModule> ioModules;
    @XmlElement(name = "IscsiDetails", required = true)
    protected List<IscsiDetail> iscsiDetails;
    @XmlElement(name = "SasDetail", required = true)
    protected List<SasDetail> sasDetail;


    /**
     * Gets the value of the ioModules property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ioModules property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIoModules().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IoModule }
     * 
     * 
     */
    public List<IoModule> getIoModules() {
        if (ioModules == null) {
            ioModules = new ArrayList<IoModule>();
        }
        return this.ioModules;
    }


    /**
     * Gets the value of the iscsiDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iscsiDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIscsiDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IscsiDetail }
     * 
     * 
     */
    public List<IscsiDetail> getIscsiDetails() {
        if (iscsiDetails == null) {
            iscsiDetails = new ArrayList<IscsiDetail>();
        }
        return this.iscsiDetails;
    }


    /**
     * Gets the value of the sasDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sasDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSasDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link SasDetail }
     * 
     * 
     */
    public List<SasDetail> getSasDetail() {
        if (sasDetail == null) {
            sasDetail = new ArrayList<SasDetail>();
        }
        return this.sasDetail;
    }

}
