/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NetworkStorageProfileController complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkStorageProfileController">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="macAddresses" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkStorageProfileController", propOrder = { "serialNumber", "macAddresses" })
public class NetworkStorageProfileController {

    @XmlElement(required = true)
    protected String serialNumber;
    @XmlElement(required = true)
    protected String macAddresses;


    /**
     * Gets the value of the serialNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSerialNumber() {
        return serialNumber;
    }


    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }


    /**
     * Gets the value of the macAddresses property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMacAddresses() {
        return macAddresses;
    }


    /**
     * Sets the value of the macAddresses property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMacAddresses(String value) {
        this.macAddresses = value;
    }

}
