/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.dell.esg.icee.common.pojo.model.storage package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this
 * class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dell.esg.icee.common.pojo.model.storage
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link StorageFirmware }
     * 
     */
    public StorageFirmware createStorageFirmware() {
        return new StorageFirmware();
    }


    /**
     * Create an instance of {@link StoragePerformance }
     * 
     */
    public StoragePerformance createStoragePerformance() {
        return new StoragePerformance();
    }


    /**
     * Create an instance of {@link DateIntValuePair }
     * 
     */
    public DateIntValuePair createDateIntValuePair() {
        return new DateIntValuePair();
    }


    /**
     * Create an instance of {@link DateLongValuePair }
     * 
     */
    public DateLongValuePair createDateLongValuePair() {
        return new DateLongValuePair();
    }


    /**
     * Create an instance of {@link StorageTopology }
     * 
     */
    public StorageTopology createStorageTopology() {
        return new StorageTopology();
    }


    /**
     * Create an instance of {@link ArrayToExpansionConnectionUtilization }
     * 
     */
    public ArrayToExpansionConnectionUtilization createArrayToExpansionConnectionUtilization() {
        return new ArrayToExpansionConnectionUtilization();
    }


    /**
     * Create an instance of {@link ExpansionToExpansionConnectionUtilization }
     * 
     */
    public ExpansionToExpansionConnectionUtilization createExpansionToExpansionConnectionUtilization() {
        return new ExpansionToExpansionConnectionUtilization();
    }


    /**
     * Create an instance of {@link StorageConsumption }
     * 
     */
    public StorageConsumption createStorageConsumption() {
        return new StorageConsumption();
    }


    /**
     * Create an instance of {@link SpaceBreakdown }
     * 
     */
    public SpaceBreakdown createSpaceBreakdown() {
        return new SpaceBreakdown();
    }


    /**
     * Create an instance of {@link FastestGrowningVolume }
     * 
     */
    public FastestGrowningVolume createFastestGrowningVolume() {
        return new FastestGrowningVolume();
    }


    /**
     * Create an instance of {@link StorageAlert }
     * 
     */
    public StorageAlert createStorageAlert() {
        return new StorageAlert();
    }


    /**
     * Create an instance of {@link StorageDetail }
     * 
     */
    public StorageDetail createStorageDetail() {
        return new StorageDetail();
    }


    /**
     * Create an instance of {@link StorageSummary }
     * 
     */
    public StorageSummary createStorageSummary() {
        return new StorageSummary();
    }


    /**
     * Create an instance of {@link Detail }
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }


    /**
     * Create an instance of {@link Controllers }
     * 
     */
    public Controllers createControllers() {
        return new Controllers();
    }


    /**
     * Create an instance of {@link HealthBase }
     * 
     */
    public HealthBase createHealthBase() {
        return new HealthBase();
    }


    /**
     * Create an instance of {@link StorageUsageOverview }
     * 
     */
    public StorageUsageOverview createStorageUsageOverview() {
        return new StorageUsageOverview();
    }


    /**
     * Create an instance of {@link Enclosure }
     * 
     */
    public Enclosure createEnclosure() {
        return new Enclosure();
    }


    /**
     * Create an instance of {@link VolumeStorageUsage }
     * 
     */
    public VolumeStorageUsage createVolumeStorageUsage() {
        return new VolumeStorageUsage();
    }


    /**
     * Create an instance of {@link VolumeSummary }
     * 
     */
    public VolumeSummary createVolumeSummary() {
        return new VolumeSummary();
    }


    /**
     * Create an instance of {@link Disk }
     * 
     */
    public Disk createDisk() {
        return new Disk();
    }


    /**
     * Create an instance of {@link DisksOverview }
     * 
     */
    public DisksOverview createDisksOverview() {
        return new DisksOverview();
    }


    /**
     * Create an instance of {@link ControllerHealth }
     * 
     */
    public ControllerHealth createControllerHealth() {
        return new ControllerHealth();
    }


    /**
     * Create an instance of {@link IscsiDetail }
     * 
     */
    public IscsiDetail createIscsiDetail() {
        return new IscsiDetail();
    }


    /**
     * Create an instance of {@link Snapshot }
     * 
     */
    public Snapshot createSnapshot() {
        return new Snapshot();
    }


    /**
     * Create an instance of {@link StorageLog }
     * 
     */
    public StorageLog createStorageLog() {
        return new StorageLog();
    }


    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }


    /**
     * Create an instance of {@link NetworkStorageProfile }
     * 
     */
    public NetworkStorageProfile createNetworkStorageProfile() {
        return new NetworkStorageProfile();
    }


    /**
     * Create an instance of {@link CreateSnapshot }
     * 
     */
    public CreateSnapshot createCreateSnapshot() {
        return new CreateSnapshot();
    }


    /**
     * Create an instance of {@link StorageOverview }
     * 
     */
    public StorageOverview createStorageOverview() {
        return new StorageOverview();
    }


    /**
     * Create an instance of {@link Temperature }
     * 
     */
    public Temperature createTemperature() {
        return new Temperature();
    }


    /**
     * Create an instance of {@link StorageHardwareInventory }
     * 
     */
    public StorageHardwareInventory createStorageHardwareInventory() {
        return new StorageHardwareInventory();
    }


    /**
     * Create an instance of {@link DeviceInformationOverview }
     * 
     */
    public DeviceInformationOverview createDeviceInformationOverview() {
        return new DeviceInformationOverview();
    }


    /**
     * Create an instance of {@link SasDetail }
     * 
     */
    public SasDetail createSasDetail() {
        return new SasDetail();
    }


    /**
     * Create an instance of {@link VolumeGrowth }
     * 
     */
    public VolumeGrowth createVolumeGrowth() {
        return new VolumeGrowth();
    }


    /**
     * Create an instance of {@link UpdateSnapshot }
     * 
     */
    public UpdateSnapshot createUpdateSnapshot() {
        return new UpdateSnapshot();
    }


    /**
     * Create an instance of {@link IOPort }
     * 
     */
    public IOPort createIOPort() {
        return new IOPort();
    }


    /**
     * Create an instance of {@link NetworkStorageProfileController }
     * 
     */
    public NetworkStorageProfileController createNetworkStorageProfileController() {
        return new NetworkStorageProfileController();
    }


    /**
     * Create an instance of {@link StorageHealth }
     * 
     */
    public StorageHealth createStorageHealth() {
        return new StorageHealth();
    }


    /**
     * Create an instance of {@link SnapshotSchedule }
     * 
     */
    public SnapshotSchedule createSnapshotSchedule() {
        return new SnapshotSchedule();
    }


    /**
     * Create an instance of {@link StorageActivity }
     * 
     */
    public StorageActivity createStorageActivity() {
        return new StorageActivity();
    }


    /**
     * Create an instance of {@link DetailBase }
     * 
     */
    public DetailBase createDetailBase() {
        return new DetailBase();
    }


    /**
     * Create an instance of {@link IoModule }
     * 
     */
    public IoModule createIoModule() {
        return new IoModule();
    }


    /**
     * Create an instance of {@link CoolingFan }
     * 
     */
    public CoolingFan createCoolingFan() {
        return new CoolingFan();
    }


    /**
     * Create an instance of {@link VolumeGrowthOverview }
     * 
     */
    public VolumeGrowthOverview createVolumeGrowthOverview() {
        return new VolumeGrowthOverview();
    }


    /**
     * Create an instance of {@link Controller }
     * 
     */
    public Controller createController() {
        return new Controller();
    }


    /**
     * Create an instance of {@link ControllersHealth }
     * 
     */
    public ControllersHealth createControllersHealth() {
        return new ControllersHealth();
    }


    /**
     * Create an instance of {@link VolumesOverview }
     * 
     */
    public VolumesOverview createVolumesOverview() {
        return new VolumesOverview();
    }


    /**
     * Create an instance of {@link PowerSupply }
     * 
     */
    public PowerSupply createPowerSupply() {
        return new PowerSupply();
    }


    /**
     * Create an instance of {@link HealthNode }
     * 
     */
    public HealthNode createHealthNode() {
        return new HealthNode();
    }


    /**
     * Create an instance of {@link EnclosuresOverview }
     * 
     */
    public EnclosuresOverview createEnclosuresOverview() {
        return new EnclosuresOverview();
    }


    /**
     * Create an instance of {@link CacheCard }
     * 
     */
    public CacheCard createCacheCard() {
        return new CacheCard();
    }


    /**
     * Create an instance of {@link IpAddress }
     * 
     */
    public IpAddress createIpAddress() {
        return new IpAddress();
    }


    /**
     * Create an instance of {@link EnclosureHealth }
     * 
     */
    public EnclosureHealth createEnclosureHealth() {
        return new EnclosureHealth();
    }

}
