/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PowerSupply complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PowerSupply">
 *   &lt;complexContent>
 *     &lt;extension base="{http://esg.dell.com/icee/infrastructure/model/storage}DetailBase">
 *       &lt;sequence>
 *         &lt;element name="swapDetected" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="acFailure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dcFailure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dcOvervolt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dcUndervolt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="highTempWarning" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="highTempFailure" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowerSupply", propOrder = { "swapDetected", "acFailure", "dcFailure", "dcOvervolt", "dcUndervolt", "highTempWarning", "highTempFailure" })
public class PowerSupply extends DetailBase {

    protected boolean swapDetected;
    protected boolean acFailure;
    protected boolean dcFailure;
    protected boolean dcOvervolt;
    protected boolean dcUndervolt;
    protected boolean highTempWarning;
    protected boolean highTempFailure;


    /**
     * Gets the value of the swapDetected property.
     * 
     */
    public boolean isSwapDetected() {
        return swapDetected;
    }


    /**
     * Sets the value of the swapDetected property.
     * 
     */
    public void setSwapDetected(boolean value) {
        this.swapDetected = value;
    }


    /**
     * Gets the value of the acFailure property.
     * 
     */
    public boolean isAcFailure() {
        return acFailure;
    }


    /**
     * Sets the value of the acFailure property.
     * 
     */
    public void setAcFailure(boolean value) {
        this.acFailure = value;
    }


    /**
     * Gets the value of the dcFailure property.
     * 
     */
    public boolean isDcFailure() {
        return dcFailure;
    }


    /**
     * Sets the value of the dcFailure property.
     * 
     */
    public void setDcFailure(boolean value) {
        this.dcFailure = value;
    }


    /**
     * Gets the value of the dcOvervolt property.
     * 
     */
    public boolean isDcOvervolt() {
        return dcOvervolt;
    }


    /**
     * Sets the value of the dcOvervolt property.
     * 
     */
    public void setDcOvervolt(boolean value) {
        this.dcOvervolt = value;
    }


    /**
     * Gets the value of the dcUndervolt property.
     * 
     */
    public boolean isDcUndervolt() {
        return dcUndervolt;
    }


    /**
     * Sets the value of the dcUndervolt property.
     * 
     */
    public void setDcUndervolt(boolean value) {
        this.dcUndervolt = value;
    }


    /**
     * Gets the value of the highTempWarning property.
     * 
     */
    public boolean isHighTempWarning() {
        return highTempWarning;
    }


    /**
     * Sets the value of the highTempWarning property.
     * 
     */
    public void setHighTempWarning(boolean value) {
        this.highTempWarning = value;
    }


    /**
     * Gets the value of the highTempFailure property.
     * 
     */
    public boolean isHighTempFailure() {
        return highTempFailure;
    }


    /**
     * Sets the value of the highTempFailure property.
     * 
     */
    public void setHighTempFailure(boolean value) {
        this.highTempFailure = value;
    }

}
