/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SnapshotSchedule complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SnapshotSchedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="instanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scheduleType" type="{http://esg.dell.com/icee/infrastructure/model/storage}SnapshotScheduleType"/>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="runDaysOfWeek" type="{http://esg.dell.com/icee/infrastructure/model/storage}DaysOfWeek" maxOccurs="unbounded"/>
 *         &lt;element name="runWeeksOfMonth" type="{http://esg.dell.com/icee/infrastructure/model/storage}WeekNumber" maxOccurs="unbounded"/>
 *         &lt;element name="runDatesOfMonth" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *         &lt;element name="runMonths" type="{http://esg.dell.com/icee/infrastructure/model/storage}Months" maxOccurs="unbounded"/>
 *         &lt;element name="expiry" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expiryTimeUnit" type="{http://esg.dell.com/icee/infrastructure/model/storage}ExpiryTimeUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnapshotSchedule", propOrder = { "id", "name", "description", "instanceId", "scheduleType", "startTime", "runDaysOfWeek", "runWeeksOfMonth", "runDatesOfMonth", "runMonths", "expiry", "expiryTimeUnit" })
public class SnapshotSchedule {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String instanceId;
    @XmlElement(required = true)
    protected SnapshotScheduleType scheduleType;
    @XmlElement(required = true)
    protected String startTime;
    @XmlElement(required = true)
    protected List<DaysOfWeek> runDaysOfWeek;
    @XmlElement(required = true)
    protected List<WeekNumber> runWeeksOfMonth;
    @XmlElement(type = Integer.class)
    protected List<Integer> runDatesOfMonth;
    @XmlElement(required = true)
    protected List<Months> runMonths;
    protected int expiry;
    @XmlElement(required = true)
    protected ExpiryTimeUnit expiryTimeUnit;


    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
        return description;
    }


    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * Gets the value of the instanceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInstanceId() {
        return instanceId;
    }


    /**
     * Sets the value of the instanceId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }


    /**
     * Gets the value of the scheduleType property.
     * 
     * @return possible object is {@link SnapshotScheduleType }
     * 
     */
    public SnapshotScheduleType getScheduleType() {
        return scheduleType;
    }


    /**
     * Sets the value of the scheduleType property.
     * 
     * @param value allowed object is {@link SnapshotScheduleType }
     * 
     */
    public void setScheduleType(SnapshotScheduleType value) {
        this.scheduleType = value;
    }


    /**
     * Gets the value of the startTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStartTime() {
        return startTime;
    }


    /**
     * Sets the value of the startTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }


    /**
     * Gets the value of the runDaysOfWeek property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runDaysOfWeek property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRunDaysOfWeek().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DaysOfWeek }
     * 
     * 
     */
    public List<DaysOfWeek> getRunDaysOfWeek() {
        if (runDaysOfWeek == null) {
            runDaysOfWeek = new ArrayList<DaysOfWeek>();
        }
        return this.runDaysOfWeek;
    }


    /**
     * Gets the value of the runWeeksOfMonth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runWeeksOfMonth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRunWeeksOfMonth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link WeekNumber }
     * 
     * 
     */
    public List<WeekNumber> getRunWeeksOfMonth() {
        if (runWeeksOfMonth == null) {
            runWeeksOfMonth = new ArrayList<WeekNumber>();
        }
        return this.runWeeksOfMonth;
    }


    /**
     * Gets the value of the runDatesOfMonth property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runDatesOfMonth property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRunDatesOfMonth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Integer }
     * 
     * 
     */
    public List<Integer> getRunDatesOfMonth() {
        if (runDatesOfMonth == null) {
            runDatesOfMonth = new ArrayList<Integer>();
        }
        return this.runDatesOfMonth;
    }


    /**
     * Gets the value of the runMonths property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runMonths property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRunMonths().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Months }
     * 
     * 
     */
    public List<Months> getRunMonths() {
        if (runMonths == null) {
            runMonths = new ArrayList<Months>();
        }
        return this.runMonths;
    }


    /**
     * Gets the value of the expiry property.
     * 
     */
    public int getExpiry() {
        return expiry;
    }


    /**
     * Sets the value of the expiry property.
     * 
     */
    public void setExpiry(int value) {
        this.expiry = value;
    }


    /**
     * Gets the value of the expiryTimeUnit property.
     * 
     * @return possible object is {@link ExpiryTimeUnit }
     * 
     */
    public ExpiryTimeUnit getExpiryTimeUnit() {
        return expiryTimeUnit;
    }


    /**
     * Sets the value of the expiryTimeUnit property.
     * 
     * @param value allowed object is {@link ExpiryTimeUnit }
     * 
     */
    public void setExpiryTimeUnit(ExpiryTimeUnit value) {
        this.expiryTimeUnit = value;
    }

}
