/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class Snapshot.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Snapshot", propOrder = { "id", "instanceId", "description", "expireTime", "freezeTime", "storageSize", "storageSizeType", "percentOfActual" })
public class Snapshot {

    protected long id;
    @XmlElement(required = true)
    protected String instanceId;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String expireTime;
    @XmlElement(required = true)
    protected String freezeTime;
    protected double storageSize;
    @XmlElement(required = true)
    protected StorageSizeType storageSizeType;
    protected int percentOfActual;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the instanceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInstanceId() {
        return instanceId;
    }


    /**
     * Sets the value of the instanceId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }


    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
        return description;
    }


    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * Gets the value of the expireTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExpireTime() {
        return expireTime;
    }


    /**
     * Sets the value of the expireTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setExpireTime(String value) {
        this.expireTime = value;
    }


    /**
     * Gets the value of the freezeTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFreezeTime() {
        return freezeTime;
    }


    /**
     * Sets the value of the freezeTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFreezeTime(String value) {
        this.freezeTime = value;
    }


    /**
     * Gets the value of the storageSize property.
     *
     * @return the storage size
     */
    public double getStorageSize() {
        return storageSize;
    }


    /**
     * Sets the value of the storageSize property.
     *
     * @param value the new storage size
     */
    public void setStorageSize(double value) {
        this.storageSize = value;
    }


    /**
     * Gets the value of the storageSizeType property.
     * 
     * @return possible object is {@link StorageSizeType }
     * 
     */
    public StorageSizeType getStorageSizeType() {
        return storageSizeType;
    }


    /**
     * Sets the value of the storageSizeType property.
     * 
     * @param value allowed object is {@link StorageSizeType }
     * 
     */
    public void setStorageSizeType(StorageSizeType value) {
        this.storageSizeType = value;
    }


    /**
     * Gets the value of the percentOfActual property.
     *
     * @return the percent of actual
     */
    public int getPercentOfActual() {
        return percentOfActual;
    }


    /**
     * Sets the value of the percentOfActual property.
     *
     * @param value the new percent of actual
     */
    public void setPercentOfActual(int value) {
        this.percentOfActual = value;
    }

}
