/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arrayToExpansionConnectionUtilizations" type="{http://esg.dell.com/icee/infrastructure/model/storage}ArrayToExpansionConnectionUtilization" maxOccurs="unbounded"/>
 *         &lt;element name="expansionToExpansionConnectionUtilizations" type="{http://esg.dell.com/icee/infrastructure/model/storage}ExpansionToExpansionConnectionUtilization" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "arrayToExpansionConnectionUtilizations", "expansionToExpansionConnectionUtilizations" })
@XmlRootElement(name = "StorageTopology")
public class StorageTopology {

    @XmlElement(required = true)
    protected List<ArrayToExpansionConnectionUtilization> arrayToExpansionConnectionUtilizations;
    @XmlElement(required = true)
    protected List<ExpansionToExpansionConnectionUtilization> expansionToExpansionConnectionUtilizations;


    /**
     * Gets the value of the arrayToExpansionConnectionUtilizations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrayToExpansionConnectionUtilizations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getArrayToExpansionConnectionUtilizations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ArrayToExpansionConnectionUtilization }
     * 
     * 
     */
    public List<ArrayToExpansionConnectionUtilization> getArrayToExpansionConnectionUtilizations() {
        if (arrayToExpansionConnectionUtilizations == null) {
            arrayToExpansionConnectionUtilizations = new ArrayList<ArrayToExpansionConnectionUtilization>();
        }
        return this.arrayToExpansionConnectionUtilizations;
    }


    /**
     * Gets the value of the expansionToExpansionConnectionUtilizations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expansionToExpansionConnectionUtilizations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getExpansionToExpansionConnectionUtilizations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ExpansionToExpansionConnectionUtilization }
     * 
     * 
     */
    public List<ExpansionToExpansionConnectionUtilization> getExpansionToExpansionConnectionUtilizations() {
        if (expansionToExpansionConnectionUtilizations == null) {
            expansionToExpansionConnectionUtilizations = new ArrayList<ExpansionToExpansionConnectionUtilization>();
        }
        return this.expansionToExpansionConnectionUtilizations;
    }

}
