/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for StorageUsageOverview complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StorageUsageOverview">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alertThresholdSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="availableSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="allocatedSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="badSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="configuredSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="freeSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="savingVsRaidTen" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="storageAlertThreshold" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="systemSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="usedSpace" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StorageUsageOverview", propOrder = { "alertThresholdSpace", "availableSpace", "allocatedSpace", "badSpace", "configuredSpace", "freeSpace", "savingVsRaidTen", "storageAlertThreshold", "systemSpace", "usedSpace", "time" })
public class StorageUsageOverview {

    protected long alertThresholdSpace;
    protected long availableSpace;
    protected long allocatedSpace;
    protected long badSpace;
    protected long configuredSpace;
    protected long freeSpace;
    protected long savingVsRaidTen;
    protected long storageAlertThreshold;
    protected long systemSpace;
    protected long usedSpace;
    @XmlElement(required = true)
    protected String time;


    /**
     * Gets the value of the alertThresholdSpace property.
     * 
     */
    public long getAlertThresholdSpace() {
        return alertThresholdSpace;
    }


    /**
     * Sets the value of the alertThresholdSpace property.
     * 
     */
    public void setAlertThresholdSpace(long value) {
        this.alertThresholdSpace = value;
    }


    /**
     * Gets the value of the availableSpace property.
     * 
     */
    public long getAvailableSpace() {
        return availableSpace;
    }


    /**
     * Sets the value of the availableSpace property.
     * 
     */
    public void setAvailableSpace(long value) {
        this.availableSpace = value;
    }


    /**
     * Gets the value of the allocatedSpace property.
     * 
     */
    public long getAllocatedSpace() {
        return allocatedSpace;
    }


    /**
     * Sets the value of the allocatedSpace property.
     * 
     */
    public void setAllocatedSpace(long value) {
        this.allocatedSpace = value;
    }


    /**
     * Gets the value of the badSpace property.
     * 
     */
    public long getBadSpace() {
        return badSpace;
    }


    /**
     * Sets the value of the badSpace property.
     * 
     */
    public void setBadSpace(long value) {
        this.badSpace = value;
    }


    /**
     * Gets the value of the configuredSpace property.
     * 
     */
    public long getConfiguredSpace() {
        return configuredSpace;
    }


    /**
     * Sets the value of the configuredSpace property.
     * 
     */
    public void setConfiguredSpace(long value) {
        this.configuredSpace = value;
    }


    /**
     * Gets the value of the freeSpace property.
     * 
     */
    public long getFreeSpace() {
        return freeSpace;
    }


    /**
     * Sets the value of the freeSpace property.
     * 
     */
    public void setFreeSpace(long value) {
        this.freeSpace = value;
    }


    /**
     * Gets the value of the savingVsRaidTen property.
     * 
     */
    public long getSavingVsRaidTen() {
        return savingVsRaidTen;
    }


    /**
     * Sets the value of the savingVsRaidTen property.
     * 
     */
    public void setSavingVsRaidTen(long value) {
        this.savingVsRaidTen = value;
    }


    /**
     * Gets the value of the storageAlertThreshold property.
     * 
     */
    public long getStorageAlertThreshold() {
        return storageAlertThreshold;
    }


    /**
     * Sets the value of the storageAlertThreshold property.
     * 
     */
    public void setStorageAlertThreshold(long value) {
        this.storageAlertThreshold = value;
    }


    /**
     * Gets the value of the systemSpace property.
     * 
     */
    public long getSystemSpace() {
        return systemSpace;
    }


    /**
     * Sets the value of the systemSpace property.
     * 
     */
    public void setSystemSpace(long value) {
        this.systemSpace = value;
    }


    /**
     * Gets the value of the usedSpace property.
     * 
     */
    public long getUsedSpace() {
        return usedSpace;
    }


    /**
     * Sets the value of the usedSpace property.
     * 
     */
    public void setUsedSpace(long value) {
        this.usedSpace = value;
    }


    /**
     * Gets the value of the time property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTime() {
        return time;
    }


    /**
     * Sets the value of the time property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTime(String value) {
        this.time = value;
    }

}
