/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for StorageAlertCategory.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="StorageAlertCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Storage"/>
 *     &lt;enumeration value="System"/>
 *     &lt;enumeration value="Hardware"/>
 *     &lt;enumeration value="Connectivity"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StorageAlertCategory")
@XmlEnum
public enum StorageAlertCategory {

    @XmlEnumValue("Storage")
    STORAGE("Storage"), @XmlEnumValue("System")
    SYSTEM("System"), @XmlEnumValue("Hardware")
    HARDWARE("Hardware"), @XmlEnumValue("Connectivity")
    CONNECTIVITY("Connectivity");
    private final String value;


    StorageAlertCategory(String v) {
        value = v;
    }


    public String value() {
        return value;
    }


    public static StorageAlertCategory fromValue(String v) {
        for (StorageAlertCategory c : StorageAlertCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
