/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class Temperature.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Temperature", propOrder = { "currentTemperature", "thresholds" })
public class Temperature extends DetailBase {

    protected int currentTemperature;
    @XmlList
    @XmlElement(type = Integer.class)
    protected List<Integer> thresholds;


    /**
     * Gets the value of the currentTemperature property.
     *
     * @return the current temperature
     */
    public int getCurrentTemperature() {
        return currentTemperature;
    }


    /**
     * Sets the value of the currentTemperature property.
     *
     * @param value the new current temperature
     */
    public void setCurrentTemperature(int value) {
        this.currentTemperature = value;
    }


    /**
     * Gets the value of the thresholds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thresholds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getThresholds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Integer }
     *
     * @return the thresholds
     */
    public List<Integer> getThresholds() {
        if (thresholds == null) {
            thresholds = new ArrayList<Integer>();
        }
        return this.thresholds;
    }

}
