/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for VolumeSummary complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VolumeSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deviceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostCacheEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="snapshotProfile" type="{http://esg.dell.com/icee/infrastructure/model/storage}VolumeSnapshotProfile"/>
 *         &lt;element name="volumeGrowth" type="{http://esg.dell.com/icee/infrastructure/model/storage}VolumeGrowth"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolumeSummary", propOrder = { "serialNumber", "deviceId", "hostCacheEnabled", "snapshotProfile", "volumeGrowth" })
public class VolumeSummary {

    @XmlElement(required = true)
    protected String serialNumber;
    @XmlElement(required = true)
    protected String deviceId;
    protected boolean hostCacheEnabled;
    @XmlElement(required = true)
    protected VolumeSnapshotProfile snapshotProfile;
    @XmlElement(required = true)
    protected VolumeGrowth volumeGrowth;


    /**
     * Gets the value of the serialNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSerialNumber() {
        return serialNumber;
    }


    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }


    /**
     * Gets the value of the deviceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeviceId() {
        return deviceId;
    }


    /**
     * Sets the value of the deviceId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }


    /**
     * Gets the value of the hostCacheEnabled property.
     * 
     */
    public boolean isHostCacheEnabled() {
        return hostCacheEnabled;
    }


    /**
     * Sets the value of the hostCacheEnabled property.
     * 
     */
    public void setHostCacheEnabled(boolean value) {
        this.hostCacheEnabled = value;
    }


    /**
     * Gets the value of the snapshotProfile property.
     * 
     * @return possible object is {@link VolumeSnapshotProfile }
     * 
     */
    public VolumeSnapshotProfile getSnapshotProfile() {
        return snapshotProfile;
    }


    /**
     * Sets the value of the snapshotProfile property.
     * 
     * @param value allowed object is {@link VolumeSnapshotProfile }
     * 
     */
    public void setSnapshotProfile(VolumeSnapshotProfile value) {
        this.snapshotProfile = value;
    }


    /**
     * Gets the value of the volumeGrowth property.
     * 
     * @return possible object is {@link VolumeGrowth }
     * 
     */
    public VolumeGrowth getVolumeGrowth() {
        return volumeGrowth;
    }


    /**
     * Sets the value of the volumeGrowth property.
     * 
     * @param value allowed object is {@link VolumeGrowth }
     * 
     */
    public void setVolumeGrowth(VolumeGrowth value) {
        this.volumeGrowth = value;
    }

}
