/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class VolumeGrowth.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolumeGrowth", propOrder = { "estimatedFullTime", "activeGrowth", "snapshotSpace", "actualGrowth" })
public class VolumeGrowth {

    @XmlElement(required = true)
    protected String estimatedFullTime;
    protected long activeGrowth;
    protected long snapshotSpace;
    protected long actualGrowth;


    /**
     * Gets the value of the estimatedFullTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEstimatedFullTime() {
        return estimatedFullTime;
    }


    /**
     * Sets the value of the estimatedFullTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setEstimatedFullTime(String value) {
        this.estimatedFullTime = value;
    }


    /**
     * Gets the value of the activeGrowth property.
     *
     * @return the active growth
     */
    public long getActiveGrowth() {
        return activeGrowth;
    }


    /**
     * Sets the value of the activeGrowth property.
     *
     * @param value the new active growth
     */
    public void setActiveGrowth(long value) {
        this.activeGrowth = value;
    }


    /**
     * Gets the value of the snapshotSpace property.
     *
     * @return the snapshot space
     */
    public long getSnapshotSpace() {
        return snapshotSpace;
    }


    /**
     * Sets the value of the snapshotSpace property.
     *
     * @param value the new snapshot space
     */
    public void setSnapshotSpace(long value) {
        this.snapshotSpace = value;
    }


    /**
     * Gets the value of the actualGrowth property.
     *
     * @return the actual growth
     */
    public long getActualGrowth() {
        return actualGrowth;
    }


    /**
     * Sets the value of the actualGrowth property.
     *
     * @param value the new actual growth
     */
    public void setActualGrowth(long value) {
        this.actualGrowth = value;
    }

}
