/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.15 at 02:06:10 PM CDT 
//

package com.dell.isg.smi.commons.model.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class VolumesOverview.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolumesOverview", propOrder = { "totalVolumes", "up", "snapshots" })
public class VolumesOverview {

    protected int totalVolumes;
    protected int up;
    protected int snapshots;


    /**
     * Gets the value of the totalVolumes property.
     *
     * @return the total volumes
     */
    public int getTotalVolumes() {
        return totalVolumes;
    }


    /**
     * Sets the value of the totalVolumes property.
     *
     * @param value the new total volumes
     */
    public void setTotalVolumes(int value) {
        this.totalVolumes = value;
    }


    /**
     * Gets the value of the up property.
     *
     * @return the up
     */
    public int getUp() {
        return up;
    }


    /**
     * Sets the value of the up property.
     *
     * @param value the new up
     */
    public void setUp(int value) {
        this.up = value;
    }


    /**
     * Gets the value of the snapshots property.
     *
     * @return the snapshots
     */
    public int getSnapshots() {
        return snapshots;
    }


    /**
     * Sets the value of the snapshots property.
     *
     * @param value the new snapshots
     */
    public void setSnapshots(int value) {
        this.snapshots = value;
    }

}
