/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ChassisSummary complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChassisSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceTag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dnsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="overallHealth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iceeState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="powerState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalSlots" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="freeSlots" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChassisSummary", propOrder = { "id", "name", "serviceTag", "model", "dnsName", "location", "overallHealth", "iceeState", "powerState", "totalSlots", "freeSlots", "status", "statusMessage" })
@XmlSeeAlso({ ChassisDetail.class })
public class ChassisSummary {

    public ChassisSummary() {
        super();
        // TODO Auto-generated constructor stub
    }

    protected String id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String serviceTag;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected String dnsName;
    @XmlElement(required = true)
    protected String location;
    @XmlElement(required = true)
    protected String overallHealth;
    @XmlElement(required = true)
    protected String iceeState;
    @XmlElement(required = true)
    protected String powerState;
    protected int totalSlots;
    protected int freeSlots;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String statusMessage;


    /**
     * Gets the value of the id property.
     * 
     */
    public String getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the serviceTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceTag() {
        return serviceTag;
    }


    /**
     * Sets the value of the serviceTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceTag(String value) {
        this.serviceTag = value;
    }


    /**
     * Gets the value of the model property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModel() {
        return model;
    }


    /**
     * Sets the value of the model property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setModel(String value) {
        this.model = value;
    }


    /**
     * Gets the value of the dnsName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDnsName() {
        return dnsName;
    }


    /**
     * Sets the value of the dnsName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDnsName(String value) {
        this.dnsName = value;
    }


    /**
     * Gets the value of the location property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocation() {
        return location;
    }


    /**
     * Sets the value of the location property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLocation(String value) {
        this.location = value;
    }


    /**
     * Gets the value of the overallHealth property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOverallHealth() {
        return overallHealth;
    }


    /**
     * Sets the value of the overallHealth property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOverallHealth(String value) {
        this.overallHealth = value;
    }


    /**
     * Gets the value of the iceeState property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIceeState() {
        return iceeState;
    }


    /**
     * Sets the value of the iceeState property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIceeState(String value) {
        this.iceeState = value;
    }


    /**
     * Gets the value of the powerState property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPowerState() {
        return powerState;
    }


    /**
     * Sets the value of the powerState property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPowerState(String value) {
        this.powerState = value;
    }


    /**
     * Gets the value of the totalSlots property.
     * 
     */
    public int getTotalSlots() {
        return totalSlots;
    }


    /**
     * Sets the value of the totalSlots property.
     * 
     */
    public void setTotalSlots(int value) {
        this.totalSlots = value;
    }


    /**
     * Gets the value of the freeSlots property.
     * 
     */
    public int getFreeSlots() {
        return freeSlots;
    }


    /**
     * Sets the value of the freeSlots property.
     * 
     */
    public void setFreeSlots(int value) {
        this.freeSlots = value;
    }


    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }


    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * Gets the value of the statusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatusMessage() {
        return statusMessage;
    }


    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

}
