/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ChassisHealth complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChassisHealth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="overallHealth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mainBoards" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="storages" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="fans" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="blowers" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="powerSupplies" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="cmcs" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="switches" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="servers" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="dvds" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="ioCables" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *         &lt;element name="fpcCables" type="{http://esg.dell.com/icee/infrastructure/model/chassis}ComponentHealth" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChassisHealth", propOrder = { "overallHealth", "mainBoards", "storages", "fans", "blowers", "powerSupplies", "cmcs", "switches", "servers", "dvds", "ioCables", "fpcCables" })
public class ChassisHealth {

    public ChassisHealth() {
        super();
        // TODO Auto-generated constructor stub
    }

    @XmlElement(required = true)
    protected String overallHealth;
    @XmlElement(required = true)
    protected List<ComponentHealth> mainBoards;
    @XmlElement(required = true)
    protected List<ComponentHealth> storages;
    @XmlElement(required = true)
    protected List<ComponentHealth> fans;
    @XmlElement(required = true)
    protected List<ComponentHealth> blowers;
    @XmlElement(required = true)
    protected List<ComponentHealth> powerSupplies;
    @XmlElement(required = true)
    protected List<ComponentHealth> cmcs;
    @XmlElement(required = true)
    protected List<ComponentHealth> switches;
    @XmlElement(required = true)
    protected List<ComponentHealth> servers;
    @XmlElement(required = true)
    protected List<ComponentHealth> dvds;
    @XmlElement(required = true)
    protected List<ComponentHealth> ioCables;
    @XmlElement(required = true)
    protected List<ComponentHealth> fpcCables;


    /**
     * Gets the value of the overallHealth property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOverallHealth() {
        return overallHealth;
    }


    /**
     * Sets the value of the overallHealth property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOverallHealth(String value) {
        this.overallHealth = value;
    }


    /**
     * Gets the value of the mainBoards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mainBoards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getMainBoards().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getMainBoards() {
        if (mainBoards == null) {
            mainBoards = new ArrayList<ComponentHealth>();
        }
        return this.mainBoards;
    }


    /**
     * Gets the value of the storages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getStorages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getStorages() {
        if (storages == null) {
            storages = new ArrayList<ComponentHealth>();
        }
        return this.storages;
    }


    /**
     * Gets the value of the fans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getFans() {
        if (fans == null) {
            fans = new ArrayList<ComponentHealth>();
        }
        return this.fans;
    }


    /**
     * Gets the value of the blowers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blowers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getBlowers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getBlowers() {
        if (blowers == null) {
            blowers = new ArrayList<ComponentHealth>();
        }
        return this.blowers;
    }


    /**
     * Gets the value of the powerSupplies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the powerSupplies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPowerSupplies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getPowerSupplies() {
        if (powerSupplies == null) {
            powerSupplies = new ArrayList<ComponentHealth>();
        }
        return this.powerSupplies;
    }


    /**
     * Gets the value of the cmcs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cmcs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCmcs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getCmcs() {
        if (cmcs == null) {
            cmcs = new ArrayList<ComponentHealth>();
        }
        return this.cmcs;
    }


    /**
     * Gets the value of the switches property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the switches property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSwitches().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getSwitches() {
        if (switches == null) {
            switches = new ArrayList<ComponentHealth>();
        }
        return this.switches;
    }


    /**
     * Gets the value of the servers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the servers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getServers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getServers() {
        if (servers == null) {
            servers = new ArrayList<ComponentHealth>();
        }
        return this.servers;
    }


    /**
     * Gets the value of the dvds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dvds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDvds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getDvds() {
        if (dvds == null) {
            dvds = new ArrayList<ComponentHealth>();
        }
        return this.dvds;
    }


    /**
     * Gets the value of the ioCables property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ioCables property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIoCables().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getIoCables() {
        if (ioCables == null) {
            ioCables = new ArrayList<ComponentHealth>();
        }
        return this.ioCables;
    }


    /**
     * Gets the value of the fpcCables property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fpcCables property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFpcCables().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ComponentHealth }
     * 
     * 
     */
    public List<ComponentHealth> getFpcCables() {
        if (fpcCables == null) {
            fpcCables = new ArrayList<ComponentHealth>();
        }
        return this.fpcCables;
    }

}
