/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ChassisServerModel complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChassisServerModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="serviceTag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chassisSlotName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="healthStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="powerStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="presence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChassisServerModel", propOrder = { "id", "serviceTag", "chassisSlotName", "healthStatus", "powerStatus", "presence" })
public class ChassisServerModel {

    public ChassisServerModel() {
        super();
        // TODO Auto-generated constructor stub
    }

    protected long id;
    @XmlElement(required = true)
    protected String serviceTag;
    @XmlElement(required = true)
    protected String chassisSlotName;
    @XmlElement(required = true)
    protected String healthStatus;
    @XmlElement(required = true)
    protected String powerStatus;
    @XmlElement(required = true)
    protected String presence;


    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the serviceTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceTag() {
        return serviceTag;
    }


    /**
     * Sets the value of the serviceTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceTag(String value) {
        this.serviceTag = value;
    }


    /**
     * Gets the value of the chassisSlotName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getChassisSlotName() {
        return chassisSlotName;
    }


    /**
     * Sets the value of the chassisSlotName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setChassisSlotName(String value) {
        this.chassisSlotName = value;
    }


    /**
     * Gets the value of the healthStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHealthStatus() {
        return healthStatus;
    }


    /**
     * Sets the value of the healthStatus property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setHealthStatus(String value) {
        this.healthStatus = value;
    }


    /**
     * Gets the value of the powerStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPowerStatus() {
        return powerStatus;
    }


    /**
     * Sets the value of the powerStatus property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPowerStatus(String value) {
        this.powerStatus = value;
    }


    /**
     * Gets the value of the presence property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPresence() {
        return presence;
    }


    /**
     * Sets the value of the presence property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPresence(String value) {
        this.presence = value;
    }

}
