/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class ChassisIkvmModel.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChassisIkvm", propOrder = { "id", "name", "manufacturer", "partNumber", "powerStatus", "firmwareVersion", "frontPanelEnabled", "health" })
public class ChassisIkvmModel {

    /**
     * Instantiates a new chassis ikvm model.
     */
    public ChassisIkvmModel() {
        super();
    }

    protected long id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String manufacturer;
    @XmlElement(required = true)
    protected String partNumber;
    @XmlElement(required = true)
    protected PowerStatus powerStatus;
    @XmlElement(required = true)
    protected String firmwareVersion;
    protected int frontPanelEnabled;
    @XmlElement(required = true)
    protected String health;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the manufacturer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManufacturer() {
        return manufacturer;
    }


    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }


    /**
     * Gets the value of the partNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPartNumber() {
        return partNumber;
    }


    /**
     * Sets the value of the partNumber property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPartNumber(String value) {
        this.partNumber = value;
    }


    /**
     * Gets the value of the powerStatus property.
     * 
     * @return possible object is {@link PowerStatus }
     * 
     */
    public PowerStatus getPowerStatus() {
        return powerStatus;
    }


    /**
     * Sets the value of the powerStatus property.
     * 
     * @param value allowed object is {@link PowerStatus }
     * 
     */
    public void setPowerStatus(PowerStatus value) {
        this.powerStatus = value;
    }


    /**
     * Gets the value of the firmwareVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }


    /**
     * Sets the value of the firmwareVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFirmwareVersion(String value) {
        this.firmwareVersion = value;
    }


    /**
     * Gets the value of the frontPanelEnabled property.
     *
     * @return the front panel enabled
     */
    public int getFrontPanelEnabled() {
        return frontPanelEnabled;
    }


    /**
     * Sets the value of the frontPanelEnabled property.
     *
     * @param value the new front panel enabled
     */
    public void setFrontPanelEnabled(int value) {
        this.frontPanelEnabled = value;
    }


    /**
     * Gets the value of the health property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHealth() {
        return health;
    }


    /**
     * Sets the value of the health property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setHealth(String value) {
        this.health = value;
    }

}
