/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class ChassisStashStorage.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChassisStashStorage", propOrder = { "id", "slotNumber", "slotName", "health", "model", "serviceTag", "assetTag", "numberOfControllers", "storageMode", "intrusionState", "presence", "powerStatus" })
public class ChassisStashStorage {

    /**
     * Instantiates a new chassis stash storage.
     */
    public ChassisStashStorage() {
        super();
    }

    protected long id;
    protected int slotNumber;
    @XmlElement(required = true)
    protected String slotName;
    @XmlElement(required = true)
    protected String health;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected String serviceTag;
    @XmlElement(required = true)
    protected String assetTag;
    protected int numberOfControllers;
    @XmlElement(required = true)
    protected String storageMode;
    @XmlElement(required = true)
    protected String intrusionState;
    @XmlElement(required = true)
    protected String presence;
    @XmlElement(required = true)
    protected PowerStatus powerStatus;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the slotNumber property.
     *
     * @return the slot number
     */
    public int getSlotNumber() {
        return slotNumber;
    }


    /**
     * Sets the value of the slotNumber property.
     *
     * @param value the new slot number
     */
    public void setSlotNumber(int value) {
        this.slotNumber = value;
    }


    /**
     * Gets the value of the slotName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSlotName() {
        return slotName;
    }


    /**
     * Sets the value of the slotName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSlotName(String value) {
        this.slotName = value;
    }


    /**
     * Gets the value of the health property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHealth() {
        return health;
    }


    /**
     * Sets the value of the health property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setHealth(String value) {
        this.health = value;
    }


    /**
     * Gets the value of the model property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModel() {
        return model;
    }


    /**
     * Sets the value of the model property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setModel(String value) {
        this.model = value;
    }


    /**
     * Gets the value of the serviceTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceTag() {
        return serviceTag;
    }


    /**
     * Sets the value of the serviceTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceTag(String value) {
        this.serviceTag = value;
    }


    /**
     * Gets the value of the assetTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetTag() {
        return assetTag;
    }


    /**
     * Sets the value of the assetTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAssetTag(String value) {
        this.assetTag = value;
    }


    /**
     * Gets the value of the numberOfControllers property.
     *
     * @return the number of controllers
     */
    public int getNumberOfControllers() {
        return numberOfControllers;
    }


    /**
     * Sets the value of the numberOfControllers property.
     *
     * @param value the new number of controllers
     */
    public void setNumberOfControllers(int value) {
        this.numberOfControllers = value;
    }


    /**
     * Gets the value of the storageMode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStorageMode() {
        return storageMode;
    }


    /**
     * Sets the value of the storageMode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStorageMode(String value) {
        this.storageMode = value;
    }


    /**
     * Gets the value of the intrusionState property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIntrusionState() {
        return intrusionState;
    }


    /**
     * Sets the value of the intrusionState property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIntrusionState(String value) {
        this.intrusionState = value;
    }


    /**
     * Gets the value of the presence property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPresence() {
        return presence;
    }


    /**
     * Sets the value of the presence property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPresence(String value) {
        this.presence = value;
    }


    /**
     * Gets the value of the powerStatus property.
     * 
     * @return possible object is {@link PowerStatus }
     * 
     */
    public PowerStatus getPowerStatus() {
        return powerStatus;
    }


    /**
     * Sets the value of the powerStatus property.
     * 
     * @param value allowed object is {@link PowerStatus }
     * 
     */
    public void setPowerStatus(PowerStatus value) {
        this.powerStatus = value;
    }

}
