/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The Class ChassisTemperatureSensor.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChassisTemperatureSensor", propOrder = { "id", "sensorUnits", "sensorName", "status", "reading", "lc", "uc", "lw", "uw", "number" })
public class ChassisTemperatureSensor {

    /**
     * Instantiates a new chassis temperature sensor.
     */
    public ChassisTemperatureSensor() {
        super();
    }

    protected long id;
    @XmlElement(required = true)
    protected String sensorUnits;
    @XmlElement(required = true)
    protected String sensorName;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String reading;
    @XmlElement(required = true)
    protected String lc;
    @XmlElement(required = true)
    protected String uc;
    @XmlElement(required = true)
    protected String lw;
    @XmlElement(required = true)
    protected String uw;
    @XmlElement(required = true)
    protected String number;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the sensorUnits property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSensorUnits() {
        return sensorUnits;
    }


    /**
     * Sets the value of the sensorUnits property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSensorUnits(String value) {
        this.sensorUnits = value;
    }


    /**
     * Gets the value of the sensorName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSensorName() {
        return sensorName;
    }


    /**
     * Sets the value of the sensorName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSensorName(String value) {
        this.sensorName = value;
    }


    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }


    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * Gets the value of the reading property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReading() {
        return reading;
    }


    /**
     * Sets the value of the reading property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setReading(String value) {
        this.reading = value;
    }


    /**
     * Gets the value of the lc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLc() {
        return lc;
    }


    /**
     * Sets the value of the lc property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLc(String value) {
        this.lc = value;
    }


    /**
     * Gets the value of the uc property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUc() {
        return uc;
    }


    /**
     * Sets the value of the uc property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setUc(String value) {
        this.uc = value;
    }


    /**
     * Gets the value of the lw property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLw() {
        return lw;
    }


    /**
     * Sets the value of the lw property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLw(String value) {
        this.lw = value;
    }


    /**
     * Gets the value of the uw property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUw() {
        return uw;
    }


    /**
     * Sets the value of the uw property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setUw(String value) {
        this.uw = value;
    }


    /**
     * Gets the value of the number property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumber() {
        return number;
    }


    /**
     * Sets the value of the number property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumber(String value) {
        this.number = value;
    }

}
