/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * The Enum ControllerStatus.
 */
@XmlType(name = "ControllerStatus")
@XmlEnum
public enum ControllerStatus {

    @XmlEnumValue("Online")
    ONLINE("Online"), @XmlEnumValue("Offline")
    OFFLINE("Offline");
    private final String value;


    /**
     * Instantiates a new controller status.
     *
     * @param v the v
     */
    ControllerStatus(String v) {
        value = v;
    }


    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return value;
    }


    /**
     * From value.
     *
     * @param v the v
     * @return the controller status
     */
    public static ControllerStatus fromValue(String v) {
        for (ControllerStatus c : ControllerStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
