/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * The Enum DevicePowerState.
 */
@XmlType(name = "DevicePowerState")
@XmlEnum
public enum DevicePowerState {

    @XmlEnumValue("On")
    ON("On"), @XmlEnumValue("Off")
    OFF("Off"), @XmlEnumValue("Power Off Soft")
    POWER_OFF_SOFT("Power Off Soft"), @XmlEnumValue("Power Cycle Soft")
    POWER_CYCLE_SOFT("Power Cycle Soft"), @XmlEnumValue("Master Bus Reset")
    MASTER_BUS_RESET("Master Bus Reset"), @XmlEnumValue("Diagnostic Interrupt")
    DIAGNOSTIC_INTERRUPT("Diagnostic Interrupt"), @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;


    /**
     * Instantiates a new device power state.
     *
     * @param v the v
     */
    DevicePowerState(String v) {
        value = v;
    }


    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return value;
    }


    /**
     * From value.
     *
     * @param v the v
     * @return the device power state
     */
    public static DevicePowerState fromValue(String v) {
        for (DevicePowerState c : DevicePowerState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
