/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 12:15:24 AM CDT 
//

package com.dell.isg.smi.commons.model.commons.chassis.inventory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PowerStatus.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="PowerStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="On"/>
 *     &lt;enumeration value="Off"/>
 *     &lt;enumeration value="Online"/>
 *     &lt;enumeration value="Offline"/>
 *     &lt;enumeration value="Standby"/>
 *     &lt;enumeration value="Slot Empty"/>
 *     &lt;enumeration value="Init"/>
 *     &lt;enumeration value="Diagnostics"/>
 *     &lt;enumeration value="Failed(No Input Power)"/>
 *     &lt;enumeration value="Updating"/>
 *     &lt;enumeration value="Failed"/>
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="na"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PowerStatus")
@XmlEnum
public enum PowerStatus {

    @XmlEnumValue("On")
    ON("On"), @XmlEnumValue("Off")
    OFF("Off"), @XmlEnumValue("Online")
    ONLINE("Online"), @XmlEnumValue("Offline")
    OFFLINE("Offline"), @XmlEnumValue("Standby")
    STANDBY("Standby"), @XmlEnumValue("Slot Empty")
    SLOT_EMPTY("Slot Empty"), @XmlEnumValue("Init")
    INIT("Init"), @XmlEnumValue("Diagnostics")
    DIAGNOSTICS("Diagnostics"), @XmlEnumValue("Failed(No Input Power)")
    FAILED_NO_INPUT_POWER("Failed(No Input Power)"), @XmlEnumValue("Updating")
    UPDATING("Updating"), @XmlEnumValue("Failed")
    FAILED("Failed"), @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"), @XmlEnumValue("na")
    NA("na");
    private final String value;


    PowerStatus(String v) {
        value = v;
    }


    public String value() {
        return value;
    }


    public static PowerStatus fromValue(String v) {
        for (PowerStatus c : PowerStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
