/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 01:19:11 PM CST 
//

package com.dell.isg.smi.commons.model.objectvault;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VaultItem", propOrder = { "id", "label", "payloadClassName", "payload" })
public class VaultItem {

    protected long id;
    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    protected String payloadClassName;
    @XmlElement(required = true)
    protected Object payload;


    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long id) {
        this.id = id;
    }


    /**
     * Gets the value of the label property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLabel() {
        return label;
    }


    /**
     * Sets the value of the label property.
     * 
     * @param label allowed object is {@link String }
     * 
     */
    public void setLabel(String label) {
        this.label = label;
    }


    /**
     * Gets the value of the payloadClassName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPayloadClassName() {
        return payloadClassName;
    }


    /**
     * Sets the value of the payloadClassName property.
     * 
     * @param payloadClassName allowed object is {@link String }
     * 
     */
    public void setPayloadClassName(String payloadClassName) {
        this.payloadClassName = payloadClassName;
    }


    /**
     * Gets the value of the payload property.
     * 
     * @return possible object is {@link Object }
     * 
     */
    public Object getPayload() {
        return payload;
    }


    /**
     * Sets the value of the payload property.
     * 
     * @param value allowed object is {@link Object }
     * 
     */
    public void setPayload(Object object) {
        this.payload = object;
    }

}
