/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

/**
 * The Class HwBattery.
 */
public class HwBattery {

    public HwBattery() {
        super();
    }

    protected long id;

    protected String fqdd;

    protected String status;

    protected String probeName;

    protected String state;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the fqdd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFqdd() {
        return fqdd;
    }


    /**
     * Sets the value of the fqdd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFqdd(String value) {
        this.fqdd = value;
    }


    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }


    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * Gets the value of the probeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProbeName() {
        return probeName;
    }


    /**
     * Sets the value of the probeName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setProbeName(String value) {
        this.probeName = value;
    }


    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getState() {
        return state;
    }


    /**
     * Sets the value of the state property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setState(String value) {
        this.state = value;
    }

}
