/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

public class HwController {

    public HwController() {
        super();
        // TODO Auto-generated constructor stub
    }

    protected long id;

    protected String bus = null;
    protected String cacheSizeInMB = null;
    protected String cacheCadeCapability = null;
    protected String controllerFirmwareVersion = null;
    protected String device = null;
    protected String deviceCardDataBusWidth = null;
    protected String deviceCardManufacturer = null;
    protected String deviceCardSlotLength = null;
    protected String deviceCardSlotType = null;
    protected String deviceDescription = null;
    protected String driverVersion = null;
    protected String encryptionCapability = null;
    protected String encryptionMode = null;
    protected String fQDD = null;
    protected String function = null;
    protected String instanceID = null;
    protected String keyID = null;
    protected String lastSystemInventoryTime = null;
    protected String lastUpdateTime = null;
    protected String maxAvailablePciLinkSpeed = null;
    protected String maxPossiblePciLinkSpeed = null;
    protected String PCIDeviceID = null;
    protected String PCISlot = null;
    protected String PCISubDeviceID = null;
    protected String PCISubVendorID = null;
    protected String PCIVendorID = null;
    protected String patrolReadState = null;
    protected String primaryStatus = null;
    protected String productName = null;
    protected String realtimeCapability = null;
    protected String rollUpStatus = null;
    protected String SASAddress = null;
    protected String securityStatus = null;
    protected String slicedVDCapability = null;
    protected String supportControllerBootMode = null;
    protected String supportEnhancedAutoForeignImport = null;
    protected String supportRaid10UnevenSpans = null;
    protected String t10piCapability = null;
    protected String possibleSpeed;
    protected String patrolReadMode;
    protected String ccMode;
    protected String ccRate;
    protected String copyBackMode;
    protected String bgiRate;
    protected String rebuildRate;
    protected String batteryState;
    protected String preservedCache;
    protected String batteryStatus;


    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


    public String getBus() {
        return bus;
    }


    public void setBus(String bus) {
        this.bus = bus;
    }


    public String getCacheSizeInMB() {
        return cacheSizeInMB;
    }


    public void setCacheSizeInMB(String cacheSizeInMB) {
        this.cacheSizeInMB = cacheSizeInMB;
    }


    public String getCacheCadeCapability() {
        return cacheCadeCapability;
    }


    public void setCacheCadeCapability(String cacheCadeCapability) {
        this.cacheCadeCapability = cacheCadeCapability;
    }


    public String getControllerFirmwareVersion() {
        return controllerFirmwareVersion;
    }


    public void setControllerFirmwareVersion(String controllerFirmwareVersion) {
        this.controllerFirmwareVersion = controllerFirmwareVersion;
    }


    public String getDevice() {
        return device;
    }


    public void setDevice(String device) {
        this.device = device;
    }


    public String getDeviceCardDataBusWidth() {
        return deviceCardDataBusWidth;
    }


    public void setDeviceCardDataBusWidth(String deviceCardDataBusWidth) {
        this.deviceCardDataBusWidth = deviceCardDataBusWidth;
    }


    public String getDeviceCardManufacturer() {
        return deviceCardManufacturer;
    }


    public void setDeviceCardManufacturer(String deviceCardManufacturer) {
        this.deviceCardManufacturer = deviceCardManufacturer;
    }


    public String getDeviceCardSlotLength() {
        return deviceCardSlotLength;
    }


    public void setDeviceCardSlotLength(String deviceCardSlotLength) {
        this.deviceCardSlotLength = deviceCardSlotLength;
    }


    public String getDeviceCardSlotType() {
        return deviceCardSlotType;
    }


    public void setDeviceCardSlotType(String deviceCardSlotType) {
        this.deviceCardSlotType = deviceCardSlotType;
    }


    public String getDeviceDescription() {
        return deviceDescription;
    }


    public void setDeviceDescription(String deviceDescription) {
        this.deviceDescription = deviceDescription;
    }


    public String getDriverVersion() {
        return driverVersion;
    }


    public void setDriverVersion(String driverVersion) {
        this.driverVersion = driverVersion;
    }


    public String getEncryptionCapability() {
        return encryptionCapability;
    }


    public void setEncryptionCapability(String encryptionCapability) {
        this.encryptionCapability = encryptionCapability;
    }


    public String getEncryptionMode() {
        return encryptionMode;
    }


    public void setEncryptionMode(String encryptionMode) {
        this.encryptionMode = encryptionMode;
    }


    public String getfQDD() {
        return fQDD;
    }


    public void setfQDD(String fQDD) {
        this.fQDD = fQDD;
    }


    public String getFunction() {
        return function;
    }


    public void setFunction(String function) {
        this.function = function;
    }


    public String getInstanceID() {
        return instanceID;
    }


    public void setInstanceID(String instanceID) {
        this.instanceID = instanceID;
    }


    public String getKeyID() {
        return keyID;
    }


    public void setKeyID(String keyID) {
        this.keyID = keyID;
    }


    public String getLastSystemInventoryTime() {
        return lastSystemInventoryTime;
    }


    public void setLastSystemInventoryTime(String lastSystemInventoryTime) {
        this.lastSystemInventoryTime = lastSystemInventoryTime;
    }


    public String getLastUpdateTime() {
        return lastUpdateTime;
    }


    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }


    public String getMaxAvailablePciLinkSpeed() {
        return maxAvailablePciLinkSpeed;
    }


    public void setMaxAvailablePciLinkSpeed(String maxAvailablePciLinkSpeed) {
        this.maxAvailablePciLinkSpeed = maxAvailablePciLinkSpeed;
    }


    public String getMaxPossiblePciLinkSpeed() {
        return maxPossiblePciLinkSpeed;
    }


    public void setMaxPossiblePciLinkSpeed(String maxPossiblePciLinkSpeed) {
        this.maxPossiblePciLinkSpeed = maxPossiblePciLinkSpeed;
    }


    public String getPCIDeviceID() {
        return PCIDeviceID;
    }


    public void setPCIDeviceID(String PCIDeviceID) {
        this.PCIDeviceID = PCIDeviceID;
    }


    public String getPCISlot() {
        return PCISlot;
    }


    public void setPCISlot(String PCISlot) {
        this.PCISlot = PCISlot;
    }


    public String getPCISubDeviceID() {
        return PCISubDeviceID;
    }


    public void setPCISubDeviceID(String PCISubDeviceID) {
        this.PCISubDeviceID = PCISubDeviceID;
    }


    public String getPCISubVendorID() {
        return PCISubVendorID;
    }


    public void setPCISubVendorID(String PCISubVendorID) {
        this.PCISubVendorID = PCISubVendorID;
    }


    public String getPCIVendorID() {
        return PCIVendorID;
    }


    public void setPCIVendorID(String PCIVendorID) {
        this.PCIVendorID = PCIVendorID;
    }


    public String getPatrolReadState() {
        return patrolReadState;
    }


    public void setPatrolReadState(String patrolReadState) {
        this.patrolReadState = patrolReadState;
    }


    public String getPrimaryStatus() {
        return primaryStatus;
    }


    public void setPrimaryStatus(String primaryStatus) {
        this.primaryStatus = primaryStatus;
    }


    public String getProductName() {
        return productName;
    }


    public void setProductName(String productName) {
        this.productName = productName;
    }


    public String getRealtimeCapability() {
        return realtimeCapability;
    }


    public void setRealtimeCapability(String realtimeCapability) {
        this.realtimeCapability = realtimeCapability;
    }


    public String getRollUpStatus() {
        return rollUpStatus;
    }


    public void setRollUpStatus(String rollUpStatus) {
        this.rollUpStatus = rollUpStatus;
    }


    public String getSASAddress() {
        return SASAddress;
    }


    public void setSASAddress(String SASAddress) {
        this.SASAddress = SASAddress;
    }


    public String getSecurityStatus() {
        return securityStatus;
    }


    public void setSecurityStatus(String securityStatus) {
        this.securityStatus = securityStatus;
    }


    public String getSlicedVDCapability() {
        return slicedVDCapability;
    }


    public void setSlicedVDCapability(String slicedVDCapability) {
        this.slicedVDCapability = slicedVDCapability;
    }


    public String getSupportControllerBootMode() {
        return supportControllerBootMode;
    }


    public void setSupportControllerBootMode(String supportControllerBootMode) {
        this.supportControllerBootMode = supportControllerBootMode;
    }


    public String getSupportEnhancedAutoForeignImport() {
        return supportEnhancedAutoForeignImport;
    }


    public void setSupportEnhancedAutoForeignImport(String supportEnhancedAutoForeignImport) {
        this.supportEnhancedAutoForeignImport = supportEnhancedAutoForeignImport;
    }


    public String getSupportRaid10UnevenSpans() {
        return supportRaid10UnevenSpans;
    }


    public void setSupportRaid10UnevenSpans(String supportRaid10UnevenSpans) {
        this.supportRaid10UnevenSpans = supportRaid10UnevenSpans;
    }


    public String getT10piCapability() {
        return t10piCapability;
    }


    public void setT10piCapability(String t10piCapability) {
        this.t10piCapability = t10piCapability;
    }


    public String getPossibleSpeed() {
        return possibleSpeed;
    }


    public void setPossibleSpeed(String possibleSpeed) {
        this.possibleSpeed = possibleSpeed;
    }


    public String getPatrolReadMode() {
        return patrolReadMode;
    }


    public void setPatrolReadMode(String patrolReadMode) {
        this.patrolReadMode = patrolReadMode;
    }


    public String getCcMode() {
        return ccMode;
    }


    public void setCcMode(String ccMode) {
        this.ccMode = ccMode;
    }


    public String getCcRate() {
        return ccRate;
    }


    public void setCcRate(String ccRate) {
        this.ccRate = ccRate;
    }


    public String getCopyBackMode() {
        return copyBackMode;
    }


    public void setCopyBackMode(String copyBackMode) {
        this.copyBackMode = copyBackMode;
    }


    public String getBgiRate() {
        return bgiRate;
    }


    public void setBgiRate(String bgiRate) {
        this.bgiRate = bgiRate;
    }


    public String getRebuildRate() {
        return rebuildRate;
    }


    public void setRebuildRate(String rebuildRate) {
        this.rebuildRate = rebuildRate;
    }


    public String getBatteryState() {
        return batteryState;
    }


    public void setBatteryState(String batteryState) {
        this.batteryState = batteryState;
    }


    public String getPreservedCache() {
        return preservedCache;
    }


    public void setPreservedCache(String preservedCache) {
        this.preservedCache = preservedCache;
    }


    public String getBatteryStatus() {
        return batteryStatus;
    }


    public void setBatteryStatus(String batteryStatus) {
        this.batteryStatus = batteryStatus;
    }
}
