/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

public class HwEnclosure {

    public HwEnclosure() {
        super();
        // TODO Auto-generated constructor stub
    }

    protected long id;

    protected String fqdd;

    protected String assetTag;

    protected String connector;
    protected int emmCount;
    protected int fanCount;

    protected String instanceId;

    protected String lastSystemInventoryTime;

    protected String lastUpdateTime;
    protected int psuCount;

    protected String primaryStatus;

    protected String productName;

    protected String rollupStatus;

    protected String serviceTag;
    protected int slotCount;
    protected int tempProbeCount;

    protected String version;

    protected String wiredOrder;

    protected String deviceDescription;

    protected String state;


    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the fqdd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFqdd() {
        return fqdd;
    }


    /**
     * Sets the value of the fqdd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFqdd(String value) {
        this.fqdd = value;
    }


    /**
     * Gets the value of the assetTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAssetTag() {
        return assetTag;
    }


    /**
     * Sets the value of the assetTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAssetTag(String value) {
        this.assetTag = value;
    }


    /**
     * Gets the value of the connector property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConnector() {
        return connector;
    }


    /**
     * Sets the value of the connector property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setConnector(String value) {
        this.connector = value;
    }


    /**
     * Gets the value of the emmCount property.
     * 
     */
    public int getEmmCount() {
        return emmCount;
    }


    /**
     * Sets the value of the emmCount property.
     * 
     */
    public void setEmmCount(int value) {
        this.emmCount = value;
    }


    /**
     * Gets the value of the fanCount property.
     * 
     */
    public int getFanCount() {
        return fanCount;
    }


    /**
     * Sets the value of the fanCount property.
     * 
     */
    public void setFanCount(int value) {
        this.fanCount = value;
    }


    /**
     * Gets the value of the instanceId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInstanceId() {
        return instanceId;
    }


    /**
     * Sets the value of the instanceId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }


    /**
     * Gets the value of the lastSystemInventoryTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastSystemInventoryTime() {
        return lastSystemInventoryTime;
    }


    /**
     * Sets the value of the lastSystemInventoryTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLastSystemInventoryTime(String value) {
        this.lastSystemInventoryTime = value;
    }


    /**
     * Gets the value of the lastUpdateTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastUpdateTime() {
        return lastUpdateTime;
    }


    /**
     * Sets the value of the lastUpdateTime property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLastUpdateTime(String value) {
        this.lastUpdateTime = value;
    }


    /**
     * Gets the value of the psuCount property.
     * 
     */
    public int getPsuCount() {
        return psuCount;
    }


    /**
     * Sets the value of the psuCount property.
     * 
     */
    public void setPsuCount(int value) {
        this.psuCount = value;
    }


    /**
     * Gets the value of the primaryStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPrimaryStatus() {
        return primaryStatus;
    }


    /**
     * Sets the value of the primaryStatus property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPrimaryStatus(String value) {
        this.primaryStatus = value;
    }


    /**
     * Gets the value of the productName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProductName() {
        return productName;
    }


    /**
     * Sets the value of the productName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setProductName(String value) {
        this.productName = value;
    }


    /**
     * Gets the value of the rollupStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRollupStatus() {
        return rollupStatus;
    }


    /**
     * Sets the value of the rollupStatus property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRollupStatus(String value) {
        this.rollupStatus = value;
    }


    /**
     * Gets the value of the serviceTag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getServiceTag() {
        return serviceTag;
    }


    /**
     * Sets the value of the serviceTag property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setServiceTag(String value) {
        this.serviceTag = value;
    }


    /**
     * Gets the value of the slotCount property.
     * 
     */
    public int getSlotCount() {
        return slotCount;
    }


    /**
     * Sets the value of the slotCount property.
     * 
     */
    public void setSlotCount(int value) {
        this.slotCount = value;
    }


    /**
     * Gets the value of the tempProbeCount property.
     * 
     */
    public int getTempProbeCount() {
        return tempProbeCount;
    }


    /**
     * Sets the value of the tempProbeCount property.
     * 
     */
    public void setTempProbeCount(int value) {
        this.tempProbeCount = value;
    }


    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersion() {
        return version;
    }


    /**
     * Sets the value of the version property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * Gets the value of the wiredOrder property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWiredOrder() {
        return wiredOrder;
    }


    /**
     * Sets the value of the wiredOrder property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setWiredOrder(String value) {
        this.wiredOrder = value;
    }


    /**
     * Gets the value of the deviceDescription property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeviceDescription() {
        return deviceDescription;
    }


    /**
     * Sets the value of the deviceDescription property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDeviceDescription(String value) {
        this.deviceDescription = value;
    }


    public String getState() {
        return state;
    }


    public void setState(String state) {
        this.state = state;
    }

}
