/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

public class HwNic {

    public HwNic() {
        super();
        // TODO Auto-generated constructor stub
    }

    protected long id;

    protected String fqdd;

    protected String autoNegotiation;

    protected String busNumber;

    protected String controllerBiosVersion;

    protected String currentMACAddress;

    protected String dataBusWidth;

    protected String deviceDescription;

    protected String deviceNumber;

    protected String fCoEOffloadMode;

    protected String fCoEWwnn;

    protected String familyVersion;

    protected String linkDuplex;

    protected String linkSpeed;

    protected String maxBandwidth;

    protected String mediaType;

    protected String minBandwidth;

    protected String nicMode;

    protected String pciDeviceID;

    protected String pciSubDeviceID;

    protected String permanentFcoMacAddress;

    protected String permanentMacAddress;

    protected String permanentiScsiMacAddress;

    protected String productName;

    protected String receiveFlowControl;

    protected String slotLength;

    protected String slotType;

    protected String transmitFlowControl;

    protected String vendorName;

    protected String virtWwn;

    protected String virtWwpn;

    protected String wwn;

    protected String wwpn;

    protected String iscsiOffloadMode;

    protected String linkStatus;

    protected String osDriverState;

    protected String macAddress;

    protected String iscsiMacAddress;

    protected String virtualMacAddress;

    protected String virtualIscsiMacAddress;

    protected String familyDriverVersion;

    protected String teaming;

    protected String iscsiOffloadSupport;

    protected String toeSupport;

    protected String legacyBootProtocol;

    protected String iscsiBootMode;

    protected String iscsiInitiatorIpAddress;

    protected String iscsiInitiatorSubnet;

    protected String iscsiInitiatorGateway;

    protected String iscsiInitiatorPrimaryDns;

    protected String iscsiInitiatorSecondryDns;

    protected String iscsiInitiatorName;


    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the fqdd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFqdd() {
        return fqdd;
    }


    /**
     * Sets the value of the fqdd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFqdd(String value) {
        this.fqdd = value;
    }


    /**
     * Gets the value of the autoNegotiation property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAutoNegotiation() {
        return autoNegotiation;
    }


    /**
     * Sets the value of the autoNegotiation property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAutoNegotiation(String value) {
        this.autoNegotiation = value;
    }


    /**
     * Gets the value of the busNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBusNumber() {
        return busNumber;
    }


    /**
     * Sets the value of the busNumber property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBusNumber(String value) {
        this.busNumber = value;
    }


    /**
     * Gets the value of the controllerBiosVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getControllerBiosVersion() {
        return controllerBiosVersion;
    }


    /**
     * Sets the value of the controllerBiosVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setControllerBiosVersion(String value) {
        this.controllerBiosVersion = value;
    }


    /**
     * Gets the value of the currentMACAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrentMACAddress() {
        return currentMACAddress;
    }


    /**
     * Sets the value of the currentMACAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCurrentMACAddress(String value) {
        this.currentMACAddress = value;
    }


    /**
     * Gets the value of the dataBusWidth property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDataBusWidth() {
        return dataBusWidth;
    }


    /**
     * Sets the value of the dataBusWidth property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDataBusWidth(String value) {
        this.dataBusWidth = value;
    }


    /**
     * Gets the value of the deviceDescription property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeviceDescription() {
        return deviceDescription;
    }


    /**
     * Sets the value of the deviceDescription property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDeviceDescription(String value) {
        this.deviceDescription = value;
    }


    /**
     * Gets the value of the deviceNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }


    /**
     * Sets the value of the deviceNumber property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDeviceNumber(String value) {
        this.deviceNumber = value;
    }


    /**
     * Gets the value of the fCoEOffloadMode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFCoEOffloadMode() {
        return fCoEOffloadMode;
    }


    /**
     * Sets the value of the fCoEOffloadMode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFCoEOffloadMode(String value) {
        this.fCoEOffloadMode = value;
    }


    /**
     * Gets the value of the fCoEWwnn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFCoEWwnn() {
        return fCoEWwnn;
    }


    /**
     * Sets the value of the fCoEWwnn property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFCoEWwnn(String value) {
        this.fCoEWwnn = value;
    }


    /**
     * Gets the value of the familyVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFamilyVersion() {
        return familyVersion;
    }


    /**
     * Sets the value of the familyVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFamilyVersion(String value) {
        this.familyVersion = value;
    }


    /**
     * Gets the value of the linkDuplex property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLinkDuplex() {
        return linkDuplex;
    }


    /**
     * Sets the value of the linkDuplex property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLinkDuplex(String value) {
        this.linkDuplex = value;
    }


    /**
     * Gets the value of the linkSpeed property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLinkSpeed() {
        return linkSpeed;
    }


    /**
     * Sets the value of the linkSpeed property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLinkSpeed(String value) {
        this.linkSpeed = value;
    }


    /**
     * Gets the value of the maxBandwidth property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMaxBandwidth() {
        return maxBandwidth;
    }


    /**
     * Sets the value of the maxBandwidth property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMaxBandwidth(String value) {
        this.maxBandwidth = value;
    }


    /**
     * Gets the value of the mediaType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMediaType() {
        return mediaType;
    }


    /**
     * Sets the value of the mediaType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMediaType(String value) {
        this.mediaType = value;
    }


    /**
     * Gets the value of the minBandwidth property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMinBandwidth() {
        return minBandwidth;
    }


    /**
     * Sets the value of the minBandwidth property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMinBandwidth(String value) {
        this.minBandwidth = value;
    }


    /**
     * Gets the value of the nicMode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNicMode() {
        return nicMode;
    }


    /**
     * Sets the value of the nicMode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNicMode(String value) {
        this.nicMode = value;
    }


    /**
     * Gets the value of the pciDeviceID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPciDeviceID() {
        return pciDeviceID;
    }


    /**
     * Sets the value of the pciDeviceID property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPciDeviceID(String value) {
        this.pciDeviceID = value;
    }


    /**
     * Gets the value of the pciSubDeviceID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPciSubDeviceID() {
        return pciSubDeviceID;
    }


    /**
     * Sets the value of the pciSubDeviceID property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPciSubDeviceID(String value) {
        this.pciSubDeviceID = value;
    }


    /**
     * Gets the value of the permanentFcoMacAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPermanentFcoMacAddress() {
        return permanentFcoMacAddress;
    }


    /**
     * Sets the value of the permanentFcoMacAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPermanentFcoMacAddress(String value) {
        this.permanentFcoMacAddress = value;
    }


    /**
     * Gets the value of the permanentMacAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPermanentMacAddress() {
        return permanentMacAddress;
    }


    /**
     * Sets the value of the permanentMacAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPermanentMacAddress(String value) {
        this.permanentMacAddress = value;
    }


    /**
     * Gets the value of the permanentiScsiMacAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPermanentiScsiMacAddress() {
        return permanentiScsiMacAddress;
    }


    /**
     * Sets the value of the permanentiScsiMacAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPermanentiScsiMacAddress(String value) {
        this.permanentiScsiMacAddress = value;
    }


    /**
     * Gets the value of the productName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProductName() {
        return productName;
    }


    /**
     * Sets the value of the productName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setProductName(String value) {
        this.productName = value;
    }


    /**
     * Gets the value of the receiveFlowControl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReceiveFlowControl() {
        return receiveFlowControl;
    }


    /**
     * Sets the value of the receiveFlowControl property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setReceiveFlowControl(String value) {
        this.receiveFlowControl = value;
    }


    /**
     * Gets the value of the slotLength property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSlotLength() {
        return slotLength;
    }


    /**
     * Sets the value of the slotLength property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSlotLength(String value) {
        this.slotLength = value;
    }


    /**
     * Gets the value of the slotType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSlotType() {
        return slotType;
    }


    /**
     * Sets the value of the slotType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSlotType(String value) {
        this.slotType = value;
    }


    /**
     * Gets the value of the transmitFlowControl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTransmitFlowControl() {
        return transmitFlowControl;
    }


    /**
     * Sets the value of the transmitFlowControl property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTransmitFlowControl(String value) {
        this.transmitFlowControl = value;
    }


    /**
     * Gets the value of the vendorName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVendorName() {
        return vendorName;
    }


    /**
     * Sets the value of the vendorName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }


    /**
     * Gets the value of the virtWwn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVirtWwn() {
        return virtWwn;
    }


    /**
     * Sets the value of the virtWwn property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVirtWwn(String value) {
        this.virtWwn = value;
    }


    /**
     * Gets the value of the virtWwpn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVirtWwpn() {
        return virtWwpn;
    }


    /**
     * Sets the value of the virtWwpn property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVirtWwpn(String value) {
        this.virtWwpn = value;
    }


    /**
     * Gets the value of the wwn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWwn() {
        return wwn;
    }


    /**
     * Sets the value of the wwn property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setWwn(String value) {
        this.wwn = value;
    }


    /**
     * Gets the value of the wwpn property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWwpn() {
        return wwpn;
    }


    /**
     * Sets the value of the wwpn property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setWwpn(String value) {
        this.wwpn = value;
    }


    /**
     * Gets the value of the iscsiOffloadMode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiOffloadMode() {
        return iscsiOffloadMode;
    }


    /**
     * Sets the value of the iscsiOffloadMode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiOffloadMode(String value) {
        this.iscsiOffloadMode = value;
    }


    /**
     * Gets the value of the linkStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLinkStatus() {
        return linkStatus;
    }


    /**
     * Sets the value of the linkStatus property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLinkStatus(String value) {
        this.linkStatus = value;
    }


    /**
     * Gets the value of the osDriverState property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOsDriverState() {
        return osDriverState;
    }


    /**
     * Sets the value of the osDriverState property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOsDriverState(String value) {
        this.osDriverState = value;
    }


    /**
     * Gets the value of the macAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMacAddress() {
        return macAddress;
    }


    /**
     * Sets the value of the macAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMacAddress(String value) {
        this.macAddress = value;
    }


    /**
     * Gets the value of the iscsiMacAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiMacAddress() {
        return iscsiMacAddress;
    }


    /**
     * Sets the value of the iscsiMacAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiMacAddress(String value) {
        this.iscsiMacAddress = value;
    }


    /**
     * Gets the value of the virtualMacAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVirtualMacAddress() {
        return virtualMacAddress;
    }


    /**
     * Sets the value of the virtualMacAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVirtualMacAddress(String value) {
        this.virtualMacAddress = value;
    }


    /**
     * Gets the value of the virtualIscsiMacAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVirtualIscsiMacAddress() {
        return virtualIscsiMacAddress;
    }


    /**
     * Sets the value of the virtualIscsiMacAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVirtualIscsiMacAddress(String value) {
        this.virtualIscsiMacAddress = value;
    }


    /**
     * Gets the value of the familyDriverVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFamilyDriverVersion() {
        return familyDriverVersion;
    }


    /**
     * Sets the value of the familyDriverVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFamilyDriverVersion(String value) {
        this.familyDriverVersion = value;
    }


    /**
     * Gets the value of the teaming property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTeaming() {
        return teaming;
    }


    /**
     * Sets the value of the teaming property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTeaming(String value) {
        this.teaming = value;
    }


    /**
     * Gets the value of the iscsiOffloadSupport property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiOffloadSupport() {
        return iscsiOffloadSupport;
    }


    /**
     * Sets the value of the iscsiOffloadSupport property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiOffloadSupport(String value) {
        this.iscsiOffloadSupport = value;
    }


    /**
     * Gets the value of the toeSupport property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getToeSupport() {
        return toeSupport;
    }


    /**
     * Sets the value of the toeSupport property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setToeSupport(String value) {
        this.toeSupport = value;
    }


    /**
     * Gets the value of the legacyBootProtocol property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLegacyBootProtocol() {
        return legacyBootProtocol;
    }


    /**
     * Sets the value of the legacyBootProtocol property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLegacyBootProtocol(String value) {
        this.legacyBootProtocol = value;
    }


    /**
     * Gets the value of the iscsiBootMode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiBootMode() {
        return iscsiBootMode;
    }


    /**
     * Sets the value of the iscsiBootMode property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiBootMode(String value) {
        this.iscsiBootMode = value;
    }


    /**
     * Gets the value of the iscsiInitiatorIpAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiInitiatorIpAddress() {
        return iscsiInitiatorIpAddress;
    }


    /**
     * Sets the value of the iscsiInitiatorIpAddress property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiInitiatorIpAddress(String value) {
        this.iscsiInitiatorIpAddress = value;
    }


    /**
     * Gets the value of the iscsiInitiatorSubnet property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiInitiatorSubnet() {
        return iscsiInitiatorSubnet;
    }


    /**
     * Sets the value of the iscsiInitiatorSubnet property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiInitiatorSubnet(String value) {
        this.iscsiInitiatorSubnet = value;
    }


    /**
     * Gets the value of the iscsiInitiatorGateway property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiInitiatorGateway() {
        return iscsiInitiatorGateway;
    }


    /**
     * Sets the value of the iscsiInitiatorGateway property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiInitiatorGateway(String value) {
        this.iscsiInitiatorGateway = value;
    }


    /**
     * Gets the value of the iscsiInitiatorPrimaryDns property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiInitiatorPrimaryDns() {
        return iscsiInitiatorPrimaryDns;
    }


    /**
     * Sets the value of the iscsiInitiatorPrimaryDns property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiInitiatorPrimaryDns(String value) {
        this.iscsiInitiatorPrimaryDns = value;
    }


    /**
     * Gets the value of the iscsiInitiatorSecondryDns property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiInitiatorSecondryDns() {
        return iscsiInitiatorSecondryDns;
    }


    /**
     * Sets the value of the iscsiInitiatorSecondryDns property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiInitiatorSecondryDns(String value) {
        this.iscsiInitiatorSecondryDns = value;
    }


    /**
     * Gets the value of the iscsiInitiatorName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIscsiInitiatorName() {
        return iscsiInitiatorName;
    }


    /**
     * Sets the value of the iscsiInitiatorName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIscsiInitiatorName(String value) {
        this.iscsiInitiatorName = value;
    }

}
