/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

public class HwPhysicalDisk {

    public HwPhysicalDisk() {
        super();
        // TODO Auto-generated constructor stub
    }

    protected String BlockSizeInBytes;
    protected String BusProtocol;
    protected String Connector;
    protected String DeviceDescription;
    protected String DriveFormFactor;
    protected String FQDD;
    protected String FreeSizeInBytes;
    protected String HotSpareStatus;
    protected String InstanceID;
    protected String LastSystemInventoryTime;
    protected String LastUpdateTime;
    protected String Manufacturer;
    protected String ManufacturingDay;
    protected String ManufacturingWeek;
    protected String ManufacturingYear;
    protected String MaxCapableSpeed;
    protected String MediaType;
    protected String Model;
    protected String OperationName;
    protected String OperationPercentComplete;
    protected String PPID;
    protected String PredictiveFailureState;
    protected String PrimaryStatus;
    protected String RaidStatus;
    protected String RemainingRatedWriteEndurance;
    protected String Revision;
    protected String RollupStatus;
    protected String SASAddress;
    protected String SecurityState;
    protected String SerialNumber;
    protected String SizeInBytes;
    protected String Slot;
    protected String SupportedEncryptionTypes;
    protected String T10PICapability;
    protected String UsedSizeInBytes;


    public String getBlockSizeInBytes() {
        return BlockSizeInBytes;
    }


    public void setBlockSizeInBytes(String blockSizeInBytes) {
        BlockSizeInBytes = blockSizeInBytes;
    }


    public String getBusProtocol() {
        return BusProtocol;
    }


    public void setBusProtocol(String busProtocol) {
        BusProtocol = busProtocol;
    }


    public String getConnector() {
        return Connector;
    }


    public void setConnector(String connector) {
        Connector = connector;
    }


    public String getDeviceDescription() {
        return DeviceDescription;
    }


    public void setDeviceDescription(String deviceDescription) {
        DeviceDescription = deviceDescription;
    }


    public String getDriveFormFactor() {
        return DriveFormFactor;
    }


    public void setDriveFormFactor(String driveFormFactor) {
        DriveFormFactor = driveFormFactor;
    }


    public String getFQDD() {
        return FQDD;
    }


    public void setFQDD(String FQDD) {
        this.FQDD = FQDD;
    }


    public String getFreeSizeInBytes() {
        return FreeSizeInBytes;
    }


    public void setFreeSizeInBytes(String freeSizeInBytes) {
        FreeSizeInBytes = freeSizeInBytes;
    }


    public String getHotSpareStatus() {
        return HotSpareStatus;
    }


    public void setHotSpareStatus(String hotSpareStatus) {
        HotSpareStatus = hotSpareStatus;
    }


    public String getInstanceID() {
        return InstanceID;
    }


    public void setInstanceID(String instanceID) {
        InstanceID = instanceID;
    }


    public String getLastSystemInventoryTime() {
        return LastSystemInventoryTime;
    }


    public void setLastSystemInventoryTime(String lastSystemInventoryTime) {
        LastSystemInventoryTime = lastSystemInventoryTime;
    }


    public String getLastUpdateTime() {
        return LastUpdateTime;
    }


    public void setLastUpdateTime(String lastUpdateTime) {
        LastUpdateTime = lastUpdateTime;
    }


    public String getManufacturer() {
        return Manufacturer;
    }


    public void setManufacturer(String manufacturer) {
        Manufacturer = manufacturer;
    }


    public String getManufacturingDay() {
        return ManufacturingDay;
    }


    public void setManufacturingDay(String manufacturingDay) {
        ManufacturingDay = manufacturingDay;
    }


    public String getManufacturingWeek() {
        return ManufacturingWeek;
    }


    public void setManufacturingWeek(String manufacturingWeek) {
        ManufacturingWeek = manufacturingWeek;
    }


    public String getManufacturingYear() {
        return ManufacturingYear;
    }


    public void setManufacturingYear(String manufacturingYear) {
        ManufacturingYear = manufacturingYear;
    }


    public String getMaxCapableSpeed() {
        return MaxCapableSpeed;
    }


    public void setMaxCapableSpeed(String maxCapableSpeed) {
        MaxCapableSpeed = maxCapableSpeed;
    }


    public String getMediaType() {
        return MediaType;
    }


    public void setMediaType(String mediaType) {
        MediaType = mediaType;
    }


    public String getModel() {
        return Model;
    }


    public void setModel(String model) {
        Model = model;
    }


    public String getOperationName() {
        return OperationName;
    }


    public void setOperationName(String operationName) {
        OperationName = operationName;
    }


    public String getOperationPercentComplete() {
        return OperationPercentComplete;
    }


    public void setOperationPercentComplete(String operationPercentComplete) {
        OperationPercentComplete = operationPercentComplete;
    }


    public String getPPID() {
        return PPID;
    }


    public void setPPID(String PPID) {
        this.PPID = PPID;
    }


    public String getPredictiveFailureState() {
        return PredictiveFailureState;
    }


    public void setPredictiveFailureState(String predictiveFailureState) {
        PredictiveFailureState = predictiveFailureState;
    }


    public String getPrimaryStatus() {
        return PrimaryStatus;
    }


    public void setPrimaryStatus(String primaryStatus) {
        PrimaryStatus = primaryStatus;
    }


    public String getRaidStatus() {
        return RaidStatus;
    }


    public void setRaidStatus(String raidStatus) {
        RaidStatus = raidStatus;
    }


    public String getRemainingRatedWriteEndurance() {
        return RemainingRatedWriteEndurance;
    }


    public void setRemainingRatedWriteEndurance(String remainingRatedWriteEndurance) {
        RemainingRatedWriteEndurance = remainingRatedWriteEndurance;
    }


    public String getRevision() {
        return Revision;
    }


    public void setRevision(String revision) {
        Revision = revision;
    }


    public String getRollupStatus() {
        return RollupStatus;
    }


    public void setRollupStatus(String rollupStatus) {
        RollupStatus = rollupStatus;
    }


    public String getSASAddress() {
        return SASAddress;
    }


    public void setSASAddress(String SASAddress) {
        this.SASAddress = SASAddress;
    }


    public String getSecurityState() {
        return SecurityState;
    }


    public void setSecurityState(String securityState) {
        SecurityState = securityState;
    }


    public String getSerialNumber() {
        return SerialNumber;
    }


    public void setSerialNumber(String serialNumber) {
        SerialNumber = serialNumber;
    }


    public String getSizeInBytes() {
        return SizeInBytes;
    }


    public void setSizeInBytes(String sizeInBytes) {
        SizeInBytes = sizeInBytes;
    }


    public String getSlot() {
        return Slot;
    }


    public void setSlot(String slot) {
        Slot = slot;
    }


    public String getSupportedEncryptionTypes() {
        return SupportedEncryptionTypes;
    }


    public void setSupportedEncryptionTypes(String supportedEncryptionTypes) {
        SupportedEncryptionTypes = supportedEncryptionTypes;
    }


    public String getT10PICapability() {
        return T10PICapability;
    }


    public void setT10PICapability(String t10PICapability) {
        T10PICapability = t10PICapability;
    }


    public String getUsedSizeInBytes() {
        return UsedSizeInBytes;
    }


    public void setUsedSizeInBytes(String usedSizeInBytes) {
        UsedSizeInBytes = usedSizeInBytes;
    }
}
