/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

/**
 * The Class HwPsu.
 */
public class HwPsu {

    public HwPsu() {
        super();
    }

    protected long id;

    protected String fqdd;

    protected String name;

    protected String status;

    protected String manufacturer;

    protected String serialNumber;

    protected String inputWattage;

    protected String outputWattage;

    protected String firmwareVersion;

    protected String partNumber;

    protected String type;

    protected String redundancyStatus;

    protected String inputAmps;

    protected String inputVoltage;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the fqdd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFqdd() {
        return fqdd;
    }


    /**
     * Sets the value of the fqdd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFqdd(String value) {
        this.fqdd = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }


    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * Gets the value of the manufacturer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManufacturer() {
        return manufacturer;
    }


    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }


    /**
     * Gets the value of the serialNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSerialNumber() {
        return serialNumber;
    }


    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }


    /**
     * Gets the value of the inputWattage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInputWattage() {
        return inputWattage;
    }


    /**
     * Sets the value of the inputWattage property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInputWattage(String value) {
        this.inputWattage = value;
    }


    /**
     * Gets the value of the outputWattage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOutputWattage() {
        return outputWattage;
    }


    /**
     * Sets the value of the outputWattage property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOutputWattage(String value) {
        this.outputWattage = value;
    }


    /**
     * Gets the value of the firmwareVersion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }


    /**
     * Sets the value of the firmwareVersion property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFirmwareVersion(String value) {
        this.firmwareVersion = value;
    }


    /**
     * Gets the value of the partNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPartNumber() {
        return partNumber;
    }


    /**
     * Sets the value of the partNumber property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPartNumber(String value) {
        this.partNumber = value;
    }


    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType() {
        return type;
    }


    /**
     * Sets the value of the type property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * Gets the value of the redundancyStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRedundancyStatus() {
        return redundancyStatus;
    }


    /**
     * Sets the value of the redundancyStatus property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRedundancyStatus(String value) {
        this.redundancyStatus = value;
    }


    /**
     * Gets the value of the inputAmps property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInputAmps() {
        return inputAmps;
    }


    /**
     * Sets the value of the inputAmps property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInputAmps(String value) {
        this.inputAmps = value;
    }


    /**
     * Gets the value of the inputVoltage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInputVoltage() {
        return inputVoltage;
    }


    /**
     * Sets the value of the inputVoltage property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInputVoltage(String value) {
        this.inputVoltage = value;
    }

}
