/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

import java.util.ArrayList;
import java.util.List;

/**
 * The Class HwStorage.
 */
public class HwStorage {

    public HwStorage() {
        super();
    }

    protected List<HwController> controllers;

    protected List<HwEnclosure> enclosures;

    protected List<HwPhysicalDisk> physicalDisks;

    protected List<HwVirtualDisk> virtualDisks;


    /**
     * Gets the value of the controllers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controllers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getControllers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link HwController }
     *
     * @return the controllers
     */
    public List<HwController> getControllers() {
        if (controllers == null) {
            controllers = new ArrayList<HwController>();
        }
        return this.controllers;
    }


    /**
     * Gets the value of the enclosures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enclosures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getEnclosures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link HwEnclosure }
     *
     * @return the enclosures
     */
    public List<HwEnclosure> getEnclosures() {
        if (enclosures == null) {
            enclosures = new ArrayList<HwEnclosure>();
        }
        return this.enclosures;
    }


    /**
     * Gets the value of the physicalDisks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the physicalDisks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPhysicalDisks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link HwPhysicalDisk }
     *
     * @return the physical disks
     */
    public List<HwPhysicalDisk> getPhysicalDisks() {
        if (physicalDisks == null) {
            physicalDisks = new ArrayList<HwPhysicalDisk>();
        }
        return this.physicalDisks;
    }


    /**
     * Gets the value of the virtualDisks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the virtualDisks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getVirtualDisks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link HwVirtualDisk }
     *
     * @return the virtual disks
     */
    public List<HwVirtualDisk> getVirtualDisks() {
        if (virtualDisks == null) {
            virtualDisks = new ArrayList<HwVirtualDisk>();
        }
        return this.virtualDisks;
    }

}
