/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.10 at 02:30:44 PM CST 
//

package com.dell.isg.smi.commons.model.server.inventory;

/**
 * The Class HwTemperature.
 */
public class HwTemperature {

    public HwTemperature() {
        super();
    }

    protected long id;

    protected String fqdd;

    protected String status;

    protected String probeName;

    protected String reading;

    protected String min;

    protected String max;

    protected String peak;

    protected String minWarningThreshold;

    protected String maxWarningThreshold;

    protected String minCriticalThreshold;

    protected String maxCriticalThreshold;


    /**
     * Gets the value of the id property.
     *
     * @return the id
     */
    public long getId() {
        return id;
    }


    /**
     * Sets the value of the id property.
     *
     * @param value the new id
     */
    public void setId(long value) {
        this.id = value;
    }


    /**
     * Gets the value of the fqdd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFqdd() {
        return fqdd;
    }


    /**
     * Sets the value of the fqdd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFqdd(String value) {
        this.fqdd = value;
    }


    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
        return status;
    }


    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * Gets the value of the probeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProbeName() {
        return probeName;
    }


    /**
     * Sets the value of the probeName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setProbeName(String value) {
        this.probeName = value;
    }


    /**
     * Gets the value of the reading property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReading() {
        return reading;
    }


    /**
     * Sets the value of the reading property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setReading(String value) {
        this.reading = value;
    }


    /**
     * Gets the value of the min property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMin() {
        return min;
    }


    /**
     * Sets the value of the min property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMin(String value) {
        this.min = value;
    }


    /**
     * Gets the value of the max property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMax() {
        return max;
    }


    /**
     * Sets the value of the max property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMax(String value) {
        this.max = value;
    }


    /**
     * Gets the value of the peak property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPeak() {
        return peak;
    }


    /**
     * Sets the value of the peak property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPeak(String value) {
        this.peak = value;
    }


    /**
     * Gets the value of the minWarningThreshold property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMinWarningThreshold() {
        return minWarningThreshold;
    }


    /**
     * Sets the value of the minWarningThreshold property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMinWarningThreshold(String value) {
        this.minWarningThreshold = value;
    }


    /**
     * Gets the value of the maxWarningThreshold property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMaxWarningThreshold() {
        return maxWarningThreshold;
    }


    /**
     * Sets the value of the maxWarningThreshold property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMaxWarningThreshold(String value) {
        this.maxWarningThreshold = value;
    }


    /**
     * Gets the value of the minCriticalThreshold property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMinCriticalThreshold() {
        return minCriticalThreshold;
    }


    /**
     * Sets the value of the minCriticalThreshold property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMinCriticalThreshold(String value) {
        this.minCriticalThreshold = value;
    }


    /**
     * Gets the value of the maxCriticalThreshold property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMaxCriticalThreshold() {
        return maxCriticalThreshold;
    }


    /**
     * Sets the value of the maxCriticalThreshold property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMaxCriticalThreshold(String value) {
        this.maxCriticalThreshold = value;
    }

}
